### PR TITLE
[1pt] PR: Updating bathymetry-preprocessing script

### PR DESCRIPTION
**Pull request by hhs732**
This PR focuses on updating the preprocess_bathymetry.py for 3 issues: 1) the capability of preprocessing SurveyJobs that have negative depth values, 2) changing the SurveyDateStamp format, and 3) the capability of including multiple SurveyJobs for one NWM feature-id if needed. 

### Changes
- `data/bathymetry/preprocess_bathymetry.py`: Addressing 3 issues including, the capability of preprocessing SurveyJobs that have negative depth values, changing the SurveyDateStamp format, and the capability of including multiple SurveyJobs for one NWM feature-id. 

### Testing
This PR has been tested on 25 SurveyJobs over the Illinois River.

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [ ] N/A Changes are limited to a single goal (no scope creep)
- [X] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [X] `pre-commit` hooks were run locally
- [X] Any _change_ in functionality is tested
- [X] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [ ] N/A New functions are documented (with a description, list of inputs, and expected output)
- [ ] N/A Placeholder code is flagged / future todos are captured in comments
- [X] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [X] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [X] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
Deployment Plan: None other than merge code. Each survey has to be run through the script one at a time and concatenated to a bathy gpkg. This updated tool is being used to update a working copies of the master `bathymetry_adjustment_data.gpkg` in temp working directories. Each developer will be building up there own bathy gpkgs.  Periodically, likely in the summer, a separate issue card will be created to merge all working copies into a new master (or update the master) `bathymetry_adjustment_data.gpkg` .  In that issue card, they will get it it merged, clean it up, test it then that master file can be propogated to all enviros at that time. No new or updated input deployable files exist in this PR.

**Review by ZahraGhahremani — DISMISSED** [review]
I tested this PR on 36 SurveyJobs for the Upper Mississippi River. Works perfectly.

**Comment by RobHanna-NOAA** [comment]
Awesome. Let's get the current dev moved in, do a quick test on it and we should be able to get it merged in. Nice work ladies. :)

**Comment by ZahraGhahremani** [comment]
> Awesome. Let's get the current dev moved in, do a quick test on it and we should be able to get it merged in. Nice work ladies. :)

Merged it with the current dev and did a quick test. All is done :)

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
