### PR TITLE
[1pt] PR: Download USGS 3DEP Dems

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
Created a new tool to downloaded USGS 3Dep DEM's via their S3 bucket.  The new tool uses any set of gkpg files as cutlines against USGS's vrt in their AWS S3 site.  Testing was against a sets of wbd HUC4 gpkg files, each with a single polygon feature. Tests were also done against a subset of HUC8 gkpg files as well.  FIM is expected to be changed in the near future to use DEMs from USGS 3Dep instead of the current NHD rasters.

In addition, another tool was added that can take a directory of tif files and make a vrt file from them. Vrt file, which is a GDAL virtual file, but is often called a `Virtual Raster` file, allows fundamentally acts like a collection of tif files are all mosaiced as one file. By using a gdal , and likely rasterio, clip request against the vrt, it does not have to worry about huc boundaries or overlapping buffers. This will be part of the new system of clipping when we replace NHD Dems with USGS 3Dep dems.

See Issue [669](https://github.com/NOAA-OWP/inundation-mapping/issues/669).

Other changes:
- moved some files from the tools directory in to the new 'data' directory. The `data` directory reflects a code file re-organization goal (still WIP). This folder is about getting, setting, pre-processing external data (such as WBD, NHD, AWS, etc). The other files were used for previous acquiring and processing of files for the "inputs" directory. Note: The other files were not tested and are expected to require minor changes to be used again, but they are of very low use and required review and updates anyways. 
- Deleted the un-used Dockerfile.prod file.
- Added tmux as a new pre-installed Docker image app.

Note: a set of gpkg files were created based on the inputs/wbd/WBD_National.gpkg via QGIS. All HUC4 features were split to their own gkpg files to help with downloading 3Dep Dems' in more manageable sizes. The new files can be found in inputs/wbd/HUC4 directory, with files from HUC2 of 19 and 22 removed (Alaska and stray Pacific ocean area hucs).

## Additions

- `data`
   - `usgs`
      - `acquire_and_preprocess_3dep_dems.py`:  The new tool as described above. For now it is hardcoded to a set path for USGS AWS S3 vrt file but may change later for it to become parameter driven. Currently, the code is set to download 10m (1/3 arc second) data and adjusts it projection at the time of download to NAD 83 default (crs 4069).
   - `create_vrt_file.py`: This can create a vrt file (explained above) of any directory of geotiff files. While we are using it for USGS 3Dep files initially, it can be used for any geotiff file directory.

## Removals

- `Dockerfile.prod`:  No longer being used (never was used)

## Changes

- `Dockerfile`:  Added apt install for tmux. This tool will now be available in docker images and assists developers.

- `data`
   - `acquire_and_preprocess_inputs.py`:  moved from the `tools` directory but not other changes made. This file will require review (and likely updates) to be used as it has not been used in quite a while.  Note: It includes use of python native `logging` functionality so that a log file is created based on code execution. 
   - `nws`
      - `preprocess_ahps_nws.py`:  moved from the `tools` directory as part of the code file re-org. Minor updates for pathing and cleanup for the "imports" section of the file. This file will require review (and likely updates) to be used as it has not been used in quite a while.
      - `preprocess_rasters.py`: moved from the `tools` directory as part of the code file re-org. Minor updates for pathing were made. This file will require review (and likely updates) to be used as it has not been used in quite a while.
    - `usgs`
         - `preprocess_ahps_usgs.py`:  moved from the `tools` directory as part of the code file re-org. Minor updates for pathing and cleanup for the "imports" section of the file. This file will require review (and likely updates) to be used as it has not been used in quite a while.
         - `preprocess_download_usgs_grids.py`: moved from the `tools` directory as part of the code file re-org. Minor updates for pathing and cleanup for the "imports" section of the file. This file will require review (and likely updates) to be used as it has not been used in quite a while.
 - `src`
     - `utils`
         - `shared_functions.py`:  changes made were
              - Cleanup the "imports" section of the file (including a change to how the utils.shared_variables file is loaded.
              - Added `progress_bar_handler` function which can be re-used by other code files.
              - Added `get_file_names` which can create a list of files from a given directory matching a given extension. 
              - Modified `print_current_date_time` and `print_date_time_duration` and  methods to return the date time strings. These helper methods exist to help with standardization of logging and output console messages.
              - Added `print_start_header` and `print_end_header` to help with standardization of console and logging output messages.
          - `shared_variables.py`: Additions in support of near future functionality of having fim load DEM's from USGS 3DEP instead of NHD rasters.

## Testing

Various combinations of downloading data from USGS, extent cut gkps (HUC4 and some HUC8), as well as variations of input and output folder arguments.  The full CONUS plus Hawaii and Puerto Rico DEM's were downloaded.

A new docker test image was created to validate the addition of tmux.

## Screenshots

aquire_3dep_output_feed
aquire_3dep_output_folder

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
We should also test again (as part of approval) that tmux and jupyter work.

**Comment by RobHanna-NOAA** [comment]
Was able to get the vrt system working which is a very helpful tool for when we update the FIM code to use USGS 3Dep DEM files instead of NHD Raster DEMs.

**Comment by mluck** [comment]
Successfully downloaded a HUC8 DEM, created a VRT from it, and extracted a HUC10 from the VRT with the following:

```
python3 /foss_fim/data/usgs/acquire_and_preprocess_3dep_dems.py -e /data/inputs/wbd/HUC4_test/ -t /data/inputs/usgs/3dep_dems/10m_test

python3 /foss_fim/data/create_vrt_file.py -s /data/inputs/usgs/3dep_dems/10m_test/ -n "fim_seamless_3dep_huc8_test.vrt"

gdalwarp -cutline /data/inputs/huc10.gpkg -crop_to_cutline -ot Float32 -r bilinear -of "GTiff" -overwrite -co "BLOCKXSIZE=512" -co "BLOCKYSIZE=512" -co "TILED=YES" -co "COMPRESS=LZW" -co "BIGTIFF=YES" /data/inputs/usgs/3dep_dems/10m_test/fim_seamless_3dep_huc8_test.vrt /outputs/vrt_3dep_clip_12090301.tif
```

Also built new Dockerfile image and verified `tmux` is installed and working.

**Review by mluck — APPROVED** [review]

**Comment by CarsonPruitt-NOAA** [comment]
We met on Friday and decided that we're going to move forward with the EPSG:5070 projection. Can you alter the retrieval code to transform the DEMs once they are downloaded. You don't need to fix every occurrence of the old CRS for this PR since this is just the download portion. We'll fix those files with the 3DEP implementation PR.

**Comment by RobHanna-NOAA** [comment]
Can do.

So.. As my release for 3dep, I will need to make sure all inputs data (nhd, wbd, etc) is 5070 (which is fine), but I will need to keep two sets of data paths (for a few releases). The original data for fim3 (in case we need an update), and the new 5070 stuff. This will give me a chance to test my script changes for downloading and transforming data. I will likely need more drive space but will get you some numbers on amount.

Also.. if we change all data in the inputs directory for 5070, we won't need to worry about anymore transforms inside the code at processing time.

Does this all sound correct?

**Pull request merged**
