### PR TITLE
[1pt] PR: Adjust ras2fim calibration input changes

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
Quick update to match incoming ras2fim calibration output files being feed into FIM was the initial change.

There is no FIM issue card for this, but this is related to a ras2fim [PR #205](https://github.com/NOAA-OWP/ras2fim/pull/205) which also made changes to ensure compatibility. New copies of both the `reformat_ras_rating_curve_table_rel_101.csv` and `reformat_ras_rating_curve_points_rel_101.gpkg` were generated from ras2fim but retained the version of `rel_101`.

Originally, was planning to update just the two locations for newer versions of the two `reformat_ras_rating_surve...` files. Both had been update to recognize the ras2release version rel_101.

In the process of doing that, we took the opportunity to move all inputs files from params_template.env and put them into bash_variables.env as per precedence set recently.

### Changes

- `config`/`params_template.env`: moved input variables into `src/bash_variables.env`
- `src`
    - `bash_variablles.env`: Added all input variables from `params_template.env` to here and added one new one from `run_unit_wb.sh` for ras_rating_curve_points_gpkg.
    - `run_unit_wb.sh`:   Updated an input param to the usgs_gage_unit_setup.py file to point the -ras param to the updated rel_101 value now in the `src/bash_variables.env`.
    - `usgs_gage_unit_setup.py`:  Changed to drop a column no longer going to be coming from ras2fim calibration files.

### Testing

While a test set of new ras2fim calibration files were created, they were based on just one HUC (12090301) with just a few models. Then in FIM, ran fim_pipeline.sh with the same HUC.  This results in a fairly limited test but no errors were recorded.

Further, using the "rel_101" calibration files (not the new test ones), a sets of 10 HUCs were run while ensuring at least 2 HUCs matched the FIM input huc list that are also in the "rel_101" list.

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [ ] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [x] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [ ] n/a New functions are documented (with a description, list of inputs, and expected output)
- [ ] n/a Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
@RyanSpies-NOAA :  I ran a set of 20 HUCs which included two HUCs from the ras2fim calib files. I picked up warning in the log_ras2fim_rc_src_adjust.log of 
`WARNING: ras_elev_df not created - check that ras_elev_table.csv files exist in fim_dir!#########################################################`

I got this warning on earlier tests but though it was a mismatch of HUCs.  There might be problem in src_adjust_ras2fim_rating.py.

Can you take this one back over and look into it?

**Comment by RobHanna-NOAA** [comment]
Ryan found no issues in  stub testing. We will re-gen all calib files for all 7 hucs, then ras2release to merge them into one standard file for FIM, copy those over to FIM and run fim_pipeline on the same 7 huc (maybe a few extra for good measure)

**Comment by RobHanna-NOAA** [comment]
I created a full new set of calibration files from ras2fim with all 7 units (huc/crs combination), using the latest code in rasfim/reformat_ras_rating_curve.py with it's latest changes. I named the output files as: `reformat_ras_rating_curve_table_test1.csv` and `reformat_ras_rating_curve_points_test1.gpkg` and placed them in `$inputsDir/rating_curve/ras2fim_exports/`.  Next using the `dev-fix-rascalb-input` branch, I manually updated the params_template value for the ras..table_test1.csv. I also updated ras_unit_wb.sh to update the value to -ras $inputsDir/rating_curve/ras2fim_exports/reformat_ras_rating_curve_points_test1.gpkg

Then I ran fim_pipeline using the 7 ras HUCs and added 3 random more HUCs for good measure.

=========================
Outcomes:

---------------------------
For the ras rating curve table, it showed:

The logs recorded this:

Performing SRC adjustments using ras2fim rating curve database
Reading RAS2FIM point loc HAND elevation from ras_elev_table csv files...
Log file output here: /outputs/Robh_calib_ras2fim_test_3/logs/src_optimization
WARNING: ras_elev_df not created - check that ras_elev_table.csv files exist in fim_dir!
Cumulative Time = 0 min(s) and 0 sec
Thu Nov 16 16:51:59 UTC 2023

I did not chase the problem down but saw it in earlier testing and am not sure if there is a problem or not.

---------------------------
For the rating curve points, it appeared to work just fine.

I opened usgs_subset_gages.gkpg from /dev_fim_share/foss_fim/outputs/Robh_calib_ras2fim_test_3/12090301/.
I could see some values in some values in the fid_xs column so I assume it loaded the ras points just fine.

================
Two questions:
1) is there a possible problem with processing the ras rating curve table? Can you double check this for me?

2) Was I correct in how I validates that the processing of ras points is good?

**Comment by RobHanna-NOAA** [comment]
One of the ras calib files `ras_rating_curve_csv` was already a variable defined in the `params_template.env`.  Initially we decided to move the hardcoded path for the `rating_curve/ras2fim_exports/reformat_ras_rating_curve_points_rel_101.gpkg` which was in `run_unit_wb.sh` and move that as a variable in `params_template.env`.

After a bit of consideration, we used this opportunity to move all pathing for input values out of `params_template.env` to `bash_variables.env` as we continue the journey to move all input pathing to a consolidated .env file.

**Review by RyanSpies-NOAA — DISMISSED** [review]
Reviewed changes and successfully ran a test on huc `12090301` (after fixing `source` filtering issues). Approved

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
