### PR TITLE
[3pt] PR: Update base GDAL Docker image and other Python packages

### LINKED ISSUE #864: [21pt] Upgrade pandas package and others
In March 2023, a number of packages were upgraded including pandas. However pandas was not upgraded to the latest and needs to be. It is currently at pandas==1.1 and the latest version should be 1.5.3.  A quick test shows that it makes some code in eval_plots.py break. Upon upgrade, other warnings will need to be addressed and upgraded.

Also.. A review of all packages fore being in the latest editions should be done to keep current.  One package, h5py, may not even be needed anymore and can be removed (validation required).

Note: As should be the case with all python package updates,  testing needs to be done against fim_pipeline and its components, plus synthesize_test_cases.py, eval_plots.py, generate_categorical_fim.py, and test_case_by_hydro_id.py.    (possibly even against inundation_nation.py and others?)

Another issue exists for upgrading the base osgeo Ubuntu image,[ issue 840](Docker - update base osgeo image #840). An upgrade of the base osgeo image, might auto upgrade some of these packages and need to be reviewed.

### PR DESCRIPTION
**Pull request by mluck**
Updates GDAL in base Docker image from 3.1.2 to 3.4.3 and updates all Python packages to latest versions, including Pandas v.2.0.0 (closes #864). Fixes resulting errors caused by deprecation and/or other changes in dependencies. 

Notes:
- Although the most current GDAL is version 3.6.3, something in 3.5 causes an issue in TauDEM `aread8` (this has been submitted as https://github.com/dtarb/TauDEM/issues/254).
- GDAL v.3.6 upgrades the Ubuntu version from 20.04 to 22.04 which bumps the Python version from 3.8.10 to 3.10.6 so other libraries/dependencies may break with v.3.6.
- See #840 for more information.

### Changes

- `Dockerfile`: Upgrade package versions and fix `tzdata`
- `fim_post_processing.sh`: Fix typo
- `Pipfile` and `Pipfile.lock`: Update Python versions
- `src/`
    - `add_crosswalk.py`, `aggregate_by_huc.py`, `src_adjust_usgs_rating.py`, and `usgs_gage_unit_setup.py`: Change `df1.append(df2)` (deprecated) to `pd.concat([df1, df2])`
    - `build_stream_traversal.py`: Fix bug
    - `getRasterInfoNative.py`: Replace `import gdal` (deprecated) with `from osgeo import gdal`
    - `stream_branches.py`: Change deprecated indexing to `.iloc[0]` and avoid `groupby.max()` over geometry
- `tools`
    - `inundation.py`: Cleans unused `from gdal`
    - `eval_plots.py`: deprecated dataframe.append fixed and deprecated python query pattern fixed.

### Testing

Ran `fim_pipeline.sh` and `synthesize_test_cases.py`

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/docs/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
Code file review looks good, nice work. I will do some docker, pipeline, alpha testing and a couple of other minor tests before fully approving the PR, but expect it will go smooth.

**Comment by RobHanna-NOAA** [comment]
Basic BED run was fine, but if failed in post processing at USGS rating curve adjustments. 

Performing SRC adjustments using USGS rating curve database
Reading USGS gage HAND elevation from usgs_elev_table.csv files...
Log file output here: /outputs/Robh_gdal_docker_2/logs/src_optimization
Creating aggregate csv
This may take a few minutes...
Reading USGS rating curve from csv...
Duration (read usgs_rc_csv): 0:00:03.385728
Processing: 2-year NWM recurr intervals
Traceback (most recent call last):
  File "/foss_fim/src/src_adjust_usgs_rating.py", line 268, in <module>
    run_prep(run_dir,usgs_rc_filepath,nwm_recurr_filepath,debug_outputs_option,job_number)
  File "/foss_fim/src/src_adjust_usgs_rating.py", line 236, in run_prep
    usgs_df = create_usgs_rating_database(usgs_rc_filepath, usgs_elev_df, nwm_recurr_filepath, log_dir)
  File "/foss_fim/src/src_adjust_usgs_rating.py", line 110, in create_usgs_rating_database
    final_df = final_df.append(calc_df, ignore_index=True)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

Remember.. you can test your fix by just running fim_post_processing.sh

**Comment by mluck** [comment]
Regarding the error in https://github.com/NOAA-OWP/inundation-mapping/pull/889#issuecomment-1515098631, a workaround for the bug has been addressed in our code, but I've tracked the source of the error down to something that changed between versions of Pandas. In the examples below comparing two versions of Pandas (1.1.0 was our previous version and 2.0.0 is the new version), when there is a `NaN` value in the DataFrame, v.2.0.0 now returns a `NaN` instead of the count and the datatype returned is a `float` instead of an` int` as in the other cases (the cause of the bug that was observed). Not yet sure if this is a known or intended change in Pandas.

```
>>> pd.__version__
'1.1.0'
>>> pd.DataFrame({'data':[0,1,1,3]}).groupby('data').cumcount(ascending=True))
0    0
1    0
2    1
3    0
dtype: int64
>>> pd.DataFrame({'data':[np.nan,1,1,3]}).groupby('data').cumcount(ascending=True)
0    0
1    0
2    1
3    0
dtype: int64
```

```
>>> pd.__version__
'2.0.0'
>>> pd.DataFrame({'data':[0,1,1,3]}).groupby('data').cumcount(ascending=True)
0    0
1    0
2    1
3    0
dtype: int64
>>> pd.DataFrame({'data':[np.nan,1,1,3]}).groupby('data').cumcount(ascending=True)
0    NaN
1    0.0
2    1.0
3    0.0
dtype: float64
```

**Comment by RobHanna-NOAA** [comment]
Made a couple small changes against eval_plots.py based on python upgrade. I was able to test the eval_plotsl.py fix against a successful alpha domain run.

**Review by RobHanna-NOAA — APPROVED** [review]
Looks good. I did an alpha domain test on it including alpha testing and eval plots and it looks good.

**Review by RobHanna-NOAA — APPROVED** [review]
Didn't test the minor update to build_stream_traversal as it was a last minute add but the risk is very low, so let's proceed anyways.

**Pull request merged**
