### PR TITLE
[1pt] PR: Addresses duplicate DEM derived streams and hydroid bug

### PR DESCRIPTION
**Pull request by BradfordBates-NOAA**
This merge adds three lines to `add_crosswalk.py` to drop duplicates from pandas dataframes. In prior versions, the duplicate features were causing the `hydroTable.csv` to blow up in size. This addresses #617.

I suspect this bug was introduced by a recent change in pandas or geopandas versions, as I was able to reproduce the issue on previous versions (3.0.7.0) where the issue did not used to occur in versions past. More testing would need to occur to confirm this, though.

## Changes

- `add_crosswalk.py`: Added pandas `drop_duplicates` to the `output_hydro_table` and `output_flows` and `output_src` dataframes to remove duplicates. This seems to have addressed the bug. 

## Testing
I tested this feature branch at the BED scale using the UCS2 API and confirmed all nonzero exit codes.

Screenshot of outputs for 04010201. Notice that the `hydroTable.csv` is not 200GB.
image

### CODE REVIEW

**Comment by RyanSpies-NOAA** [comment]
After inspecting the hydrotable.csv for 04010201, I'm still seeing issues with duplicates. This is causing the `hydroTable.csv` file size to be significantly inflated (currently ~1gb and should be ~100mb). It appears the duplicates are introduced between the `src_base.csv` and the `src_full_crosswalked.csv`. I can see the duplicates (lesser impact) in the `src_full_crosswalked.csv` and then the issue is inflated with the `hydroTable.csv`. I suggest trying to drop the duplicates from the `src_full_crosswalked.csv` to see if that resolves the downstream impacts.

**Comment by BradfordBates-NOAA** [comment]
Fixed the issue thanks to Ryan's suggestion to remove duplicates from the `src_base`

**Review by RyanSpies-NOAA — APPROVED** [review]
I was able to successfully reproduce the outputs for huc 04010201 and did not see any duplicates in the `src_full_crosswalked.csv` or `hydroTable.csv`. Approved for merge.

**Comment by BradfordBates-NOAA** [comment]
@CarsonPruitt-NOAA This is ready to be merged.

**Pull request merged**
