### PR TITLE
Integrate GVAL In Synthesize Cases

### PR DESCRIPTION
**Pull request by GregoryPetrochenkov-NOAA**
This pull request addresses #938.  

Newest
csi_aggr_ras2fim_comp

Original
csi_aggr_ras2fim_comp

Newest Stats
image

Original Stats
image

### Changes  
- Dockerfile - Add dependencies for GVAL
- Pipfile - Add GVAL and update related dependencies
- Pipfile.lock - Setup for Docker Image builds
- run_test_case.py: Remove unused arguments and cleanup
- synthesize_test_cases.py:  Fix None comparisons and cleanup
- tools/shared_functions.py:  Add GVAL crosswalk function, add rework create_stats_from_raster, create and create_stats_from_contingency_table

### Testing
-Rigorous comparison of all output from test cases in the following catchments: 
10240002 07080105 10240010 07100006 07080208

* ALL Pass except

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x` 
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by mluck** [comment]
Nice work, GVAL seems to integrate well into `synthesize_test_cases.py`. Functionality has been verified by running `synthesize_test_cases.py` on 12090301. Metrics were identical except for order and all raster cell differences were zero.

I had to add `rioxarray` and `geocube` to the Pipfile get this to run. Also, because this branch will require a new Dockerfile, @robgpita-noaa requested that it also be tested with `certifi==23.7.22` so #951 can be incorporated into the Docker build at the same time so that was added to the Pipfile without any problems.

### Notes

- `total_area_stats.csv`: There were six additional metrics and `LIKLIHOOD` is incorrectly spelled.
- `total_area_agreement.tif`: The rasters appeared identical but the QGIS statistics were slightly different.

From `4.3.11.7`:
```
Band 1	
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=3
STATISTICS_MEAN=0.63546717859736
STATISTICS_MINIMUM=0
STATISTICS_STDDEV=1.1762940148437
STATISTICS_VALID_PERCENT=44.86
```

From `integrate_gval`:
```
Band 1	
STATISTICS_APPROXIMATE=YES
STATISTICS_MAXIMUM=4
STATISTICS_MEAN=0.52614512996847
STATISTICS_MINIMUM=0
STATISTICS_STDDEV=0.92510117448772
STATISTICS_VALID_PERCENT=49.09
```

**Review by mluck — APPROVED** [review]

**Comment by mluck** [comment]
Disregard the difference in statistics in the previous comment -- those were the default estimated statistics but the actual statistics are identical.

**Comment by GregoryPetrochenkov-NOAA** [comment]
I went ahead and added the certifi==2023.7.22 and tested to make sure everything builds and works the same.  I also fixed the typos.  Let me know if there is anything else I need to do.

**Review by mluck — APPROVED** [review]
Works with certifi and gval added to Pipfile.

Also appreciate the attention to formatting.

**Review by robgpita-noaa — COMMENTED** [review]
@GregoryPetrochenkov-NOAA Thanks for the work here! All of the code looks good to me from a stylistic perspective. Thanks for adding `certifi = "==2023.7.22"` to the `Pipfile` and running another Docker build and test. 

The only things I can see that are left would be to update the `docs/CHANGELOG.MD` & run `pytest` to ensure no unit tests are failing (highly unlikely since you didn't touch any files with associated unit tests).

**Comment by GregoryPetrochenkov-NOAA** [comment]
I just made changes to CHANGELOG.MD, however I am not able to run pytest because I do not have the capacity to download the appropriate data, nor do I have access to a remote Linux terminal as of yet.  Please advise.

**Comment by robgpita-noaa** [comment]
@GregoryPetrochenkov-NOAA Thanks for updating the `CHANGELOG.MD`. No worries on the unit tests, I checked out this PR and ran them. Everything passes.

**Comment by robgpita-noaa** [comment]
@GregoryPetrochenkov-NOAA Thanks for your collaboration, and working with me to get the unit test bugfix in, as well as running pytest on your end.

**Review by robgpita-noaa — DISMISSED** [review]

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
