### PR TITLE
[3pt] PR: Shapely upgrade

### PR DESCRIPTION
**Pull request by LauraKeys-NOAA**
This PR addresses changes to function calls needed to run upgraded Shapely library plus other related library upgrades. Upgraded libraries upgraded or removed include:

- shapely
- geopandas
- pandas
- numba
- rasterstats
- numpy
- rtree
- tqdm
- pyarrow
- pygeos (removed)
 

## Additions

- pyarrow added to list of python libraries for future parquet use

### Removals

- pygeos removed because its capabilities have been rolled into shapely

### Changes

- `Dockerfile`
- `src/build_stream_traversal.py`
- `src/add_crosswalk.py`
- `src/adjust_headwater_streams.py`
- `src/aggregate_vector_inputs.py`
- `src/clip_vectors_to_wbd.py`
- `src/derive_headwaters.py`
- `src/stream_branches.py`
- `src/split_flows.py`
- `tools/fimr_to_benchmark.py`
- `tools/tools_shared_functions.py`

### Testing

1. Tested with CatFIM on multiple sites; errors and warnings corrected and re-run
2. Individual HUC testing (08090201) for fim_pipeline; errors and warnings corrected and re-run
3. To do: Scale testing

### Mar 30: Late adjustments added:

- `Pipfile and Pipfile.lock`: merged the pip install changes into Pipfile and Pipfile.lock, plus added a new one `py7zr`.
- `Dockerfile`: Changed to use `Pipfile` and `Pipfile.lock` plus add a fix for a recent issue with whitebox. [Issue 863](https://github.com/NOAA-OWP/inundation-mapping/issues/863).

### CODE REVIEW

**Review by RobHanna-NOAA — APPROVED** [review]
Did an alpha domain run, plus ran syth and eval and it all looks good. Now, go ahead and fix the PR body and the changelog to match our current standards and we are good to go for a merge.

**Review by RobHanna-NOAA — DISMISSED** [review]
Looks awesome. Thanks Laura. We will merge it on our next build run.

**Comment by mluck** [comment]
Sierra tests ran successfully.

**Comment by mluck** [comment]
There's one more change I'd like to suggest. I'm getting the following warning which can be fixed by adding `index_parts=True` as an argument to `.explode()` -- I think this has been done elsewhere. I've verified that the warning goes away with this change.
```
/foss_fim/src/associate_levelpaths_with_levees.py:106: FutureWarning: Currently, index_parts defaults to True, but in the future, it will default to False to be consistent with Pandas. Use `index_parts=True` to keep the current behavior and True/False to silence the warning.
  row_intersections = row_intersections.explode()
```

**Comment by LauraKeys-NOAA** [comment]
Yes, we should definitely incorporate that change.

**Comment by RobHanna-NOAA** [comment]
In light of a last minute docker fix for whitebox, we are going to apply that dockerfile fix directly to this branch to ease merge issues. Also, in the same spirit, and also wanting to limit the number of near term new docker builds, Matt has asked for py7zr to e added as well.  A check for both against this branch is coming today.

**Review by mluck — APPROVED** [review]
I built an image from the new Dockerfile with whitebox fix. `fim_pipeline.sh` ran successfully.

I made a few changes to `src/associate_levelpaths_with_levees.py` to handle the Warnings that were being reported.

**Review by RobHanna-NOAA — DISMISSED** [review]
Matt and I both worked together on edits and reviewing

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
