### PR TITLE
[1pt] PR: Bug fix for extending outlets

### LINKED ISSUE #1200: [13pt] Orphan streams incorrectly extended
Outlet NWM streams were extended by snapping to the buffered WBD (#1121) to make sure they reach the edge of the DEM to ensure proper flow direction after stream burning and pit filling. However, it appears that orphan streams (e.g., disconnected from the outlet stream network) are also snapped using this procedure and cause incorrect NWM flowlines in the preclip step as a result.

## Screenshots
Example of the orphan streamline (red). The original NWM streams in blue lines; pre-clipped NWM streams in black dashed line
image

A zoomed out view with several straight NWM flowlines (black dotted lines) being snapped to the WBD buffer (black)
image

### PR DESCRIPTION
**Pull request by mluck**
Bug fix for extending outlets in order to ensure proper flow direction in depression filling algorithm introduced in #1121. This PR adds a distance criteria that in order for the end of an outlet stream to be snapped to the wbd_buffered boundary, the end point must be less than 100 meters from the WBD boundary. Fixes #1200.

Also adds missing argparse arguments so that the script can be run from the command line.

### Changes

- `data`
     - `wbd`
          - `clip_vectors_to_wbd.py`: Adds a 100 meter distance threshold to WBD to snap outlets to buffered WBD.
          - `generate_pre_clip_fim_huc8.py`: Upgrading logging system.
- `src`
     - `bash_variables.env`: Updated pre-clip input path to new pre-clip files.

### Testing

Example from HUC 18100201. Red lines are current dev (v4.5.2.3) and yellow lines are this feature branch. All of the yellow lines are coincident with the red lines, but there are some erroneous red lines that are snapped from internal outlets to the buffered WBD (thin black line). HUC8 boundary displayed in thicker black line.
image

### Deployment Plan (For developer use)

_How does the changes affect the product?_
- [ ] Code only?
- [x] Require new or adjusted data inputs? Does it have start, end and duration code (in UTC)?
- [x] If new or updated data sets, has the FIM code been updated and tested with the new/adjusted data (subset is fine, but must be a subset of the new data)?
- [x] Require new pre-clip set?
- [ ] Has new or updated python packages?
- [ ] If applicable, has a deployment plan be created with the deployment person/team?

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [x] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
@RyanSpies-NOAA : I am thinking that maybe you and Matt can pick a couple of HUCs you would like to test first. I can do a quick pre-clip run for those few hucs and run pipeline on them.  If Ryan is happy with that, I can do a fully CONUS pre-clip and we an test is as part of the next weekly build. Thoughts?

**Comment by mluck** [comment]
@RobHanna-NOAA Sounds good.

Besides 180100201, here are some other HUCs that are addressed by this PR: 01070006, 03100204, 10180014, 18030007.

**Comment by RobHanna-NOAA** [comment]
> @RobHanna-NOAA Sounds good.
> 
> Besides 180100201, here are some other HUCs that are addressed by this PR: 01070006, 03100204, 10180014, 18030007.

--------------
 Thats a pretty good set. Maybe we are ok to just go ahead and run the full pre-clip and see what we get. If worse comes to worse, we can re-run it.  When I run pre-clip, I will update `bash_variables.env` to put in the new date for `pre_clip_huc_dir=${inputsDir}/pre_clip_huc8/240502`.  Then I make sure that folder is  fully propagated to all enviros before the code merge and deploy.

What you do you think Matt... think we are good to do a full pre-clip run?

**Comment by RobHanna-NOAA** [comment]
A full set of pre-clips are in progress, so logic testing not yet available. When full new pre-clips are ready, Zahra will run a couple of hucs and validate the new WBD files, then we can approve it.

**Comment by RobHanna-NOAA** [comment]
During a full scale BED area for pre-clip, a few things bottomed out.
1)  I upgraded the logging system to a better system based on new patterns from other check-ins.
2)  I updated the `bash_variables.env` for the folder name of the new pre-clip path that will be in place when this goes live.
3) A bug was found which resulted in all Alaska HUCs failing.

File "//./foss_fim/data/wbd/generate_pre_clip_fim_huc8.py", line 380, in huc_level_clip_vectors_to_wbd
    raise Exception(f"{huc} : Error creating wbd file for {huc}: Details: {sub_proc_stderror}")
Exception: 19020203 : Error creating wbd file for 19020203: Details: Warning 1: A geometry of type MULTIPOLYGON is inserted into layer WBD_National_South_Alaska of geometry type POLYGON, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.

For more details, you can see a test run that exists in efs....fim-data/inputs/pre_clip_huc8/20240702-rob-test/.  That test was done against the huc list of /dev_small_test_8_Alaska_and_CONUS.lst

**Comment by mluck** [comment]
I ran `/foss_fim/data/wbd/generate_pre_clip_fim_huc8.py` on 19020203 and wasn't able to reproduce the error.

```
==========================================================================

 generate_pre_clip_fim_huc8.py

 	 Started: 07/05/2024 15:26:38 


	 Output Directory: /data/inputs/pre_clip_huc8/20240627/19020203 exists.  It will be overwritten, and the newly generated huc level files will be output there. 

Parallelizing HUC level wbd pre-clip vector creation. 
==========================================================================

 generate_pre_clip_fim_huc8.py

 	 Started: 07/05/2024 15:26:39 

Processing 19020203
19020203 : 
Get Vector Layers and Subset 19020203
Create wbd buffer for 19020203
Clip ocean water polygon for 19020203
Create stream buffer for 19020203
Clip levee-protected areas for 19020203
Subsetting NWM Lakes for 19020203
Failed to auto identify EPSG: 7
Subsetting NLD levee lines for 19020203
Subsetting NWM Headwater Points for 19020203
Subsetting OSM Bridges for 19020203
Create subset of osm bridges gpkg for 19020203
Subsetting NWM Streams for 19020203
 Completing Get Vector Layers and Subset: 19020203 

	 	 run time for huc 19020203: is 0:07:34

 Ended: 07/05/2024 15:34:15 

==========================================================================
	 Completed writing all huc level files 
	 	 TOTAL RUN TIME: 0:07:37
==========================================================================
```

**Comment by RobHanna-NOAA** [comment]
All hucs are now pre-clipped and am coping them to all enviros. Ready for a last minute huc test for at least one regular huc and at one Alaska.

**Review by ZahraGhahremani — APPROVED** [review]
I tested this PR using the new pre-clipped data across several HUCs (0107006, 03140203, 15010005, 18100201, 19020203, 19020800). I employed the NHDPlus sink layer to pinpoint areas where errors were likely to occur, as indicated by the brown dots in the figures below. The PR effectively addresses the previous errors. In the figures, the red lines represent results from FIM 4.5.2.0, while the green lines show the outcomes of this PR.
image
image

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
