### PR TITLE
[1pt] PR: Update README.md with new reference and grammar correction, and update CITATION.cff

### PR DESCRIPTION
**Pull request by BradfordBates-NOAA**
Updated the README.md by adding a reference to Aristizabal's recent publication. Also added an extra space in one of the reference lines.

### Changes  

- `README.md`

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [ ] Links are provided if this PR resolves an issue, or depends on another other PR
- [ ] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [ ] Any _change_ in functionality is tested
- [ ] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/docs/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Comment by fernando-aristizabal** [comment]
This looks good but also recommend updating the `CITATION.cff` file referenced in the readme which populates the "cite this repository" link on GH.

Screenshot 2023-05-10 at 10 07 10

**Comment by BradfordBates-NOAA** [comment]
Good point. We should be probably be crediting OWP as the primary author, then include your paper. I'm not seeing good examples of CITATION files in other repos, e.g. TauDEM. Do you have examples of other repos where this has been done well, i.e. both federal crediting and scientific articles? Do we need a CITATION file?

**Comment by fernando-aristizabal** [comment]
I'm not sure.

**Comment by BradfordBates-NOAA** [comment]
In my recent commit I've listed NOAA OWP as primary author in the `CITATION.cff`. @fernando-aristizabal Your paper is listed in references which I think is the more appropriate spot. If you agree please approve when you have a chance.

**Comment by fernando-aristizabal** [comment]
I'm not sure if the citation.cff file represents an actual citation.

**Comment by BradfordBates-NOAA** [comment]
It seems that there aren't clear instructions from the federal government as to what should go into the `CITATION.cff`. All I can find is this:
```
5.2.4. Metadata and documentation. In order to make code discoverable and usable by others, it is important to include metadata and documentation. Agencies shall:

a. Use the machine-readable metadata schema(s) best suited to their needs and publish their metadata in machine-readable format(s) (e.g., metadata catalogs, code repository metadata fields, a CITATION.cff file) to the extent practicable;

b. Ensure their metadata and documentation are sufficient to enable users to discover, understand, and replicate the code;

c. Use open licenses for documentation and metadata; and

d. Include a CITATION.cff file in each code repository that includes sufficient metadata to facilitate citation of the code in scholarly research."
```

All they say is "include sufficient metadata to facilitate citation of the code in scholarly research." I'll add "GitHub Repository" to the citation file. We could add the version number to the `CITATION.cff` but that will create more overhead with each merge. Probably fine.

**Comment by BradfordBates-NOAA** [comment]
I took the text above from the Federal Source Code Policy document, found on the website of the U.S. government's Office of Management and Budget.

**Comment by fernando-aristizabal** [comment]
`NOAA Office of Water Prediction. Inundation Mapping GitHub Repository (Version 4.3.9.0) [Computer software]` is missing a date and/or year as well as a URL.

**Comment by BradfordBates-NOAA** [comment]
Good call I'll add those in

**Comment by BradfordBates-NOAA** [comment]
Alright I added the URL and year: `NOAA Office of Water Prediction. Inundation Mapping (Version 4.3.9.0) [Computer software]. https://github.com/NOAA-OWP/inundation-mapping`

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
- family-names: "NOAA Office of Water Prediction"
title: "Inundation Mapping"
url: "https://github.com/NOAA-OWP/inundation-mapping"
version: 4.3.9.0
date-released: 2023
```

**Review by fernando-aristizabal — APPROVED** [review]

**Pull request merged**
