### PR TITLE
[1pt] PR: Change all occurances of `/data/outputs` to `/outputs`

### PR DESCRIPTION
**Pull request by robgpita-noaa**
Change all occurances of `/data/outputs` to `/outputs` to honor the correct volume mount directory specified when executing `docker run`.   Will close issue #813.   The primary mechanism in which we set the `/outputs` directory is in the Dockerfile. This modification was included in PR #814 :
```
- ENV outputDataDir=$dataDir/outputs
+ ENV outputDataDir=/outputs  
```

## Additions

`Dockerfile` - updated comments in relation to `projectDir=/foss_fim`
`fim_pipeline.sh` - updated comments in relation to `projectDir=/foss_fim`
`fim_pre_processing.sh` -updated comments in relation to `projectDir=/foss_fim`
`fim_post_processing.sh` - updated comments in relation to `projectDir=/foss_fim`
`README.md` - Provide documentation on starting the Docker Container, and update docs to include additional command line option for calibration database tool.   

## Changes

`src/` 
  - `usgs_gage_crosswalk.py` - added newline character to shorten commented example usage
  - `usgs_gage_unit_setup.py` - `/data/outputs/` => `/outputs/`  

`tools/` 
  - `cache_metrics.py` -  `/data/outputs/` => `/outputs/`
  - `copy_test_case_folders.py`  - `/data/outputs/` => `/outputs/`
  - `run_test_case.py` - `/data/outputs/` => `/outputs/`  

`unit_tests/*_params.json`  - `/data/outputs/` => `/outputs/` 

`unit_tests/split_flows_test.py`  - `/data/outputs/` => `/outputs/` 

## Testing

Ran `pytest` from `unit_tests/` and all passed. 
Ran `fim_pipeline.sh` for one HUC on nwcal-fim-dev1 & AWS EC2 isntance.

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
Ya, Rob P is working on the new temp directory fix, which will trigger a difference between outputDir and tempDir.  I believe he is going to reviewing all related variable names.

**Comment by RobHanna-NOAA** [comment]
@mluck : Are you getting that error against the new PR branch (aka.. dev-ouput-directory)? or against dev?

**Comment by mluck** [comment]
I was getting the error in `dev`

**Comment by robgpita-noaa** [comment]
@mluck Thanks for pointing this out. I'll make those changes in this PR.

**Comment by mluck** [comment]
> I'm getting an error running `fim_pipeline.sh` because now [`outputDataDir=/outputs`](https://github.com/NOAA-OWP/inundation-mapping/blob/dev/Dockerfile#L55) but with [`export outputRunDataDir=/$outputDataDir/$runName`](https://github.com/NOAA-OWP/inundation-mapping/blob/dev/fim_process_unit_wb.sh#L64), `outputRunDataDir` is getting two leading slashes (`//`). So I think the leading `/` in `fim_process_unit_wb.sh` should be removed (i.e., `outputRunDataDir=$outputDataDir/$runName`).

It looks like the two leading slashes in the path weren't actually causing the `No such file or directory` error that I was getting.

**Review by RobHanna-NOAA — APPROVED** [review]
Looks good other than the regularly seen //outputs but it doesn't seem to be harming anything. We should fix it some day though, but it would require a dockerfile change which we don't want at this point. We can piggy back that fix on the Shapely fix when it comes in.

I tested this against a new temp outputs directory, ran a benchmark huc and did synth and eval plots on it. All was well.

**Comment by mluck** [comment]
I think the `//outputs` change can be made [here](https://github.com/NOAA-OWP/inundation-mapping/blob/dev/fim_process_unit_wb.sh#L64) without requiring changing the Dockerfile.

**Comment by RobHanna-NOAA** [comment]
oh.. yes. sorry, you are right.  I can make that fix for Rob P (he is pretty busy today) and test it. Thanks Matt

**Comment by robgpita-noaa** [comment]
No worries @RobHanna-NOAA I made the fix in this branch/PR.

**Review by RobHanna-NOAA — APPROVED** [review]

**Comment by robgpita-noaa** [comment]
@mluck 

> I'm getting an error running `fim_pipeline.sh` because now [`outputDataDir=/outputs`](https://github.com/NOAA-OWP/inundation-mapping/blob/dev/Dockerfile#L55) but with [`export outputRunDataDir=/$outputDataDir/$runName`](https://github.com/NOAA-OWP/inundation-mapping/blob/dev/fim_process_unit_wb.sh#L64), `outputRunDataDir` is getting two leading slashes (`//`). So I think the leading `/` in `fim_process_unit_wb.sh` should be removed (i.e., `outputRunDataDir=$outputDataDir/$runName`).
> 
> Also, I think to go in line with what seems like our variable naming convention, `outputDataDir` might be renamed `outputDir` (and `outputRunDataDir` to `outputRunDir`).

Per the variable naming suggestion, I am working on another PR in reference to #798 in which all of the variables will be more consistently named.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
