### PR TITLE
[8pt] PR: Mask levee-protected areas from Relative Elevation Model

### LINKED ISSUE #684: [13pt] Mask out levee protected areas
After REM creation, we want to mask all levee protected areas to NoData. As part of this task, we'll need to download the same polygon dataset that's used in the FIM Reviewer and NWPS to have consistency with the layers that FIM users will be viewing.

As a pre-requisite, we want to download the levee-protected areas from USACE to make sure we have the most up-do-date data.

- [x] Download levee-protected polygons
- [x] Mask out protected areas from REM
- [x] Allow tributary GMS branches to still inundate in protected areas
    - This is an optional task. If we can't reliably mask out the right GMS branches, we want to err on the side of masking everything since inundating behind levees is very high-profile.

### PR DESCRIPTION
**Pull request by mluck**
Masks levee-protected areas from Relative Elevation Model on branch 0 and any 10th (and higher) order branches. Closes #684.

## Additions

- `src/gms/delineate_hydros_and_produce_HAND.sh`
    - Reprojects and creates raster subset of levee-protected areas from polygon layer
    - Uses that raster to mask/remove those areas from the Relative Elevation Model

## Changes

- `src/gms/delineate_hydros_and_produce_HAND.sh`
    - Fixes a bug in ocean/Great Lakes masking

## Testing
```
gms_run_unit.sh -s -u 11140207 -n mask-leveed-areas -c /foss_fim/config/params_matt.env -d /foss_fim/config/deny_gms_unit_default.lst

gms_run_branch.sh -s -n mask-leveed-areas -u 11140207 -c /foss_fim/config/params_matt.env -j 6 -d /foss_fim/config/deny_gms_branches_default.lst
```

### Legend
Branch "1": grayscale
Branch 0: color scale
Stream branches: colored lines
WBD boundary: black line
image

## Notes
- Levee-protected areas polygons were downloaded manually from https://levees.sec.usace.army.mil/#/levees/search/in=@nation:USA&viewType=map&resultsType=systems&advanced=true&hideList=false&eventSystem=false
- It might be possible to automate the downloading but I could only figure out how to get a list of the sites and download one site at a time
```
curl -X GET "https://levees.sec.usace.army.mil:443/api-local/leveed-areas?embed=geometry&format=geo" -H  "accept: application/json" --output LeveedAreas.json
curl -X GET "https://levees.sec.usace.army.mil:443/api-local/leveed-areas?system_id=1905004125&embed=geometry&format=geo" -H  "accept: application/json"
```

### CODE REVIEW

**Comment by mluck** [comment]
Branch 0 (whitish shade) and branches with stream order >= 10 (blackish shade) are now masked with levee-protected areas (red outlined polygons), while other branches (colored) remain unmasked as in example below from HUC 07140105:

image

**Comment by mluck** [comment]
For testing this PR you'll need a HUC with 10th order streams and also levee-protected areas. I've been using 07140101 and 07140105 for those and 11140207 for a HUC with levee-protected areas but no 10th order streams.

**Comment by CarsonPruitt-NOAA** [comment]
I'm kind of re-thinking only masking on 10th order streams because I'm now seeing that there are several lower-order streams that will be missed by this approach. Would it be possible to get the highest order stream for each HUC8 and mask the REM for that branch? The region I'm looking at is near Dayton, OH because it has plenty of levees on smaller rivers (`05080001` & `05080002`). `05080001` will be especially tricky because there are two 6th-order streams that converge into a 7th-order river.

Here's the logic I've got worked out in my head:

- If a HUC has levee-protected polygons:
    - Query the `/{HUC8}/nwm_subset_streams_levelPaths.gpkg` layer to get the highest order in that HUC
    - Each unique `levpa_id` that is in the queried layer should be listed for REM masking

**Comment by RobHanna-NOAA** [comment]
Hey Matt. Are the poly's you need already in inputs/nld_vectors/huc2_levee_poly folder? Should the input path come from there instead of LeveedArea.geojson.  Can you see if you have what you need in the poly's we already have?  If we do need this as full new data, I will make a separate issue/PR to get that data downloaded.

**Comment by mluck** [comment]
Yes, see the Notes in the original PR message for details.

**Comment by RobHanna-NOAA** [comment]
For now.. I just manually uploaded the LeevedArea.geojson file into the inputs/nld_vectors folder. I am having a few a delays on programmatically load that file, so lets go ahead with this PR approval and not have it wait for other Issue/PR that will download that file.

**Comment by RobHanna-NOAA** [comment]
Processed HUC 05080001, brought the rems and derived catchments for two of the branches with the highest stream ordered and looks at the rem's. They look good and are masked out as expected from the rem's

**Review by RobHanna-NOAA — DISMISSED** [review]
Looks good. Double checked outputs in QGIS for masking, Double checked a HUC for alpha testing and it all looks good.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
