### PR TITLE
[1pt] PR: Change Docker base image and stop Whitebox downloads

### LINKED ISSUE #1209: [8pt] Whitebox calling URL at runtime
Once again, the whitebox packages is making external calls at runtime which we can not allow. Sure enough, during one of our runs, it randomly failed because of a failed external connection call.

/outputs/fim_bathy_adj_test_11/logs/unit/07120001_unit.log:59:Unexpected error: <class 'urllib.error.URLError'>
/outputs/fim_bathy_adj_test_11/logs/unit/07120001_unit.log:81:ConnectionResetError: [Errno 104] Connection reset by peer
/outputs/fim_bathy_adj_test_11/logs/unit/07120001_unit.log:107:    raise URLError(err)
/outputs/fim_bathy_adj_test_11/logs/unit/07120001_unit.log:108:urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

(Note: HUC number not relevant)

More details;

-----------------------------------------------------------------
Creating AGREE DEM using 70 meter buffer 07120001 0
Downloading WhiteboxTools pre-compiled binary for first time use ...
Downloading WhiteboxTools binary from https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_amd64.zip
Decompressing WhiteboxTools_linux_amd64.zip ...
WhiteboxTools package directory: /usr/local/lib/python3.10/dist-packages/whitebox
Downloading testdata ...
Unexpected error: <class 'urllib.error.URLError'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/foss_fim/src/agreedem.py", line 321, in <module>
    agreedem(
  File "/foss_fim/src/agreedem.py", line 51, in agreedem
    wbt = whitebox.WhiteboxTools()
  File "/usr/local/lib/python3.10/dist-packages/whitebox/whitebox_tools.py", line 307, in __init__
    download_wbt()
  File "/usr/local/lib/python3.10/dist-packages/whitebox/whitebox_tools.py", line 253, in download_wbt
    urllib.request.urlretrieve(dep_url, os.path.join(work_dir, "DEM.dep"))
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

### LINKED ISSUE #1278: [8pt] Open JDK 17 re-appeared
On Aug 8, our security team detected that the Open JDK 17 issue has re-appear.

The security tool picked up the phrase in this folder on our servers.
Path              : /var/lib/docker/overlay2/c1e9b64d8e3f562048f29614d8adbdcd42966e1cda566edc74fc0fd9aa0bafef/diff/usr/lib/jvm/java-17-openjdk-amd64/

We no longer need open jdk17 at all.

After some experimenting, when we do a docker build, this folder re-appears, each with a random id after the overlay2 folder.

Soem experimenting was done on how this get there.

Let's look to see if there is something our docker file is building two images and maybe one of those is leaving java17 behind.  
Maybe somethign is being left behind, and it might be just a matter of uninstalling java 17 before installing java 21. It is possible and common to have multiple jdk engines on one image or servers.

Lets check out one of our AWS EC2 to see if some docker builds can re-create this folder above and if so, we can debug and fix. Without it, we might have to get creative.

### PR DESCRIPTION
**Pull request by mluck**
This PR incorporates a number of changes to the Docker environment:
- Changes Docker base image to `gdal:ubuntu-small` in order to avoid JDK from being carried over in the base image and triggering security vulnerabilities. Resolves #1278.
- Upgrades `fiona` and `jupterlab`. Closes #1270 and closes #1290.
- Eliminates `whitebox` downloading during `fim_pipeline`. Resolves #1209 and closes #1293.

During testing, it was discovered that many files which are not in the `src` directory, can no longer see the `src\utils` files. Adjusting the dockerfile to add extra values to the PYTHONPATH variable fixed it.
Note: This triggers new docker images to be made.

### Changes

- `Dockerfile`: Changes base image to `gdal:ubuntu-small-3.8.4` and removes code related to JDK
- `Pipfile` and `Pipfile.lock`: Upgrades `fiona`, `jupyterlab`, and `whitebox`
- `fim_pre_processing`: Removes `WBT_PATH` assignment
- `src/`
    - `agreedem.py` and `unique_pixel_and_allocation.py`: sets `whitebox_dir` to `WBT_PATH`

### Testing
Ran `fim_pipeline.sh` and `synthesize_test_cases.py` on HUC 03100204.

- Also ran pipeline on 12040101, including synthesize and eval_plots.

### Deployment Plan (For developer use)

_How does the changes affect the product?_
- [ ] Code only?
- [ ] If applicable, has a deployment plan be created with the deployment person/team?
- [ ] Require new or adjusted data inputs? Does it have start, end and duration code (in UTC)?
- [ ] If new or updated data sets, has the FIM code been updated and tested with the new/adjusted data (subset is fine, but must be a subset of the new data)?
- [ ] Require new pre-clip set?
- [x] Has new or updated python packages?

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
The Docker fix has been tested. Removed all images from our OWP "u" servers, had ITSG check to make sure there was no residue. Then loaded our new container from here and ITSG said it was still fixed. So we are good to go on the docker base image fix

**Comment by RobHanna-NOAA** [comment]
built the image on one of my EC2's, then ran sudo find /var/lib/docker/ -type f -name "*java-17*" to ensure it didn't pop back up. All good on that part. Doing a pipeline test next.

**Comment by mluck** [comment]
Tested the new changes by building a new Docker image and running fim_pipeline, synthesize_test_cases, and eval_plots. Verified no import error and the eval plots were created successfully.

**Review by RobHanna-NOAA — APPROVED** [review]
Matt and I went back and forth on testing and validate. All is well now

**Comment by mluck** [comment]
Note: the message `[Errno 2] No such file or directory: './whitebox_tools'` (see https://github.com/opengeos/whitebox-python/issues/72#issuecomment-2231409666) is still occurring but doesn't seem to affect the functionality of whitebox.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
