### PR TITLE
[1pt] PR: Clip branch 0 DEM-derived flowlines to terminal NWM streamlines

### LINKED ISSUE #852: [21pt] Issues around NHD "sinks"
Our flow routing workflow does not account for NHD sinks. Therefore, DEM-derived flowlines that pass sinks will get crosswalked to an incorrect NWM feature id. 

As a solution, I'm thinking that we could use the NHD sinks dataset to effectively stop the DEM-derived reaches from flowing past them. We may not be able to use all of the sink dataset, so we should look at the attributes to see how we can make sure that we're only stopping flow at the correct points. Using something like `Purpose Description = 'BurnLineEvent network end'` might work.

### Tasks:
- [x] Add a download script for the NHD sinks in `data/nhd_plus/`
    - [x] Find best data source for the sinks - preferably directly from USGS NHD+
- [x] Determine whether the sinks dataset should be filtered down to a certain type
- [x] Ensure that the locations of all of the sinks we're going to use are coincident with the terminal end of a NWM streamline
- [x] Write workflow to remove segments of the `dem_derived_reaches` that are downstream of sinks
    - [x] Should be after the [streamnet step](https://github.com/NOAA-OWP/inundation-mapping/blob/5a201355d79804dbcc8d5ba1345adc7ec73b6ee8/src/delineate_hydros_and_produce_HAND.sh#L73)
    - [x] Branch 0
    - [x] GMS branches

### PR DESCRIPTION
**Pull request by mluck**
Branch 0 DEM-derived flowlines may extend beyond termini of NWM streamlines (often where NWM streamlines end in sinks); other levelpaths/branches are clipped using NWM streamlines. This extends the clipping to branch 0 using the `to` attribute of NWM streams (where `to=0`).

The original idea was to clip the DEM-derived flowlines using an NHD sinks layer. There are several version of NHD sinks layers and it was found that the "legacy" dataset hosted at the [EPA](https://www.epa.gov/waterdata/nhdplus-national-data) correctly coincided with the NWM streamlines:
- [NHDPlusV21_NationalData_Seamless_Geodatabase_Lower48_07.7z](https://edap-ow-data-commons.s3.amazonaws.com/NHDPlusV21/Data/NationalData/NHDPlusV21_NationalData_Seamless_Geodatabase_Lower48_07.7z)
- [NHDPlusV21_NationalData_Seamless_Geodatabase_HI_PR_VI_PI_03.7z](https://edap-ow-data-commons.s3.amazonaws.com/NHDPlusV21/Data/NationalData/NHDPlusV21_NationalData_Seamless_Geodatabase_HI_PR_VI_PI_03.7z)

However, there wasn't a 1-to-1 correspondence between NHD sinks and NWM stream termini, and there were more NWM stream termini, so it was decided to use the NWM streams instead of the NHD sinks. See #852 for the full discussion. Also note that in the `dev-sinks` branch there was code developed to download the NHD sinks data in `data/nhd_plus/acquire_and_preprocess_nhdplus.py` in case that is needed in the future.

Closes #852.

### Changes
- `src/`
    - `delineate_hydros_and_produce_HAND.sh`: Added input arguments to `src/split_flows.py`
    - `split_flows.py`: Added functionality to snap and trim branch 0 flows to terminal NWM streamlines

### Testing
```
fim_pipeline.sh -u "14030003 18060002" -n dev-sinks -jh 2 -jb 3 -c /foss_fim/config/params_template.env -o -skipcal
```

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [ ] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated ([CHANGELOG](/docs/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Comment by CarsonPruitt-NOAA** [comment]
I got the following error on HUC `05130103`. I chose this one because of the presence of large NWM lakes.
```
-----------------------------------------------------------------
Split Derived Reaches 05130103 0
Mon Apr 10 17:55:27 UTC 2023
Loading data ...
trimming DEM stream to NWM branch terminus
Traceback (most recent call last):
  File "/foss_fim/src/split_flows.py", line 336, in <module>
    split_flows(**args)
  File "/foss_fim/src/utils/shared_functions.py", line 266, in wrapper
    func(*args, **kwargs)
  File "/foss_fim/src/split_flows.py", line 144, in split_flows
    flows = snap_and_trim_flow(snapped_point, flows)
  File "/foss_fim/src/split_flows.py", line 49, in snap_and_trim_flow
    nearest_index = int(sjoin_nearest['LINKNO'])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/series.py", line 129, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'int'>
Command exited with non-zero status 1
        Command being timed: "/foss_fim/src/run_unit_wb.sh"
        User time (seconds): 775.07
        System time (seconds): 99.07
        Percent of CPU this job got: 121%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 11:59.17
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 6335816
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 40
        Minor (reclaiming a frame) page faults: 35932510
        Voluntary context switches: 41925
        Involuntary context switches: 180481
        Swaps: 0
        File system inputs: 96
        File system outputs: 18480272
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
```

**Comment by mluck** [comment]
@CarsonPruitt-NOAA That's an interesting one, but not because of lakes. There's a couple complicated things going on at this location:
- The thing causing the issue is that there are two sinks on the same DEM-derived reach. The reach is first clipped at the upstream sink so the second sink doesn't find that reach but instead the next closest point is a junction so two equidistant reaches are found, hence the error. This (multiple points) can be resolved by taking the upstream reach (where the `to` ID is the ID of the downstream reach). Another thing to add would be a maximum search distance since we want to snap the end of the NWM to the parallel DEM-derived flowline (and in this case the two points are over 300 m apart) -- this would also solve the issue in this case.

image


- Additionally, the NWM (blue) and DEM-derived flowlines (yellow) diverge-- it looks like a thalweg notch case based on the dem_thalwegCond. The terminal NWM segment (black) ends in a sink. If the DEM-derived flowline was going in the correct direction (same as the NWM) then the first issue wouldn't have been a problem.

image

**Comment by mluck** [comment]
I just added a commit that restricts the distance for snapping DEM-derived flowlines to the downstream end of terminal NWM segments, currently set to 100 meters. Also, if multiple flowlines are found (occurring because of the nearest DEM-derived point occurring at a confluence of more than one reach), the downstream reach is returned for clipping.

**Comment by mluck** [comment]
@RyanSpies-NOAA You're correct, that's two NWM stream segments (black) that are split by a sink. The DEM-derived flowline in red is clipped from the rest of the flowlines (green) at the sink.
image

**Review by RobHanna-NOAA — APPROVED** [review]
Did a full alpha domain test on it and it looks fine.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
