### PR TITLE
[1pt] PR: Add `NO_VALID_CROSSWALKS` to `FIM_exit_codes`

### LINKED ISSUE #1212: [8pt] Missing catchment reaches with crosswalk files
During a full BED of 4.5.2.5, over 500 branches triggered the following error:

./logs/unit/16040203_unit.log:8074:fiona._err.CPLE_OpenFailedError: /fim_temp/fim_4_5_2_5/16040203/branches/8954000027/gw_catchments_reaches_filtered_addedAttributes_crosswalked_8954000027.gpkg: No such file or directory

Log details:
-----------------------------------------------------------------
```
Burn in bridges 16040203 8954000027
/usr/local/lib/python3.10/dist-packages/rasterstats/io.py:335: NodataWarning: Setting nodata to -999; specify nodata explicitly
  warnings.warn(
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: /fim_temp/fim_4_5_2_5/16040203/branches/8954000027/gw_catchments_reaches_filtered_addedAttributes_crosswalked_8954000027.gpkg: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/foss_fim/src/heal_bridges_osm.py", line 152, in <module>
    process_bridges_in_huc(**args)
  File "/foss_fim/src/heal_bridges_osm.py", line 63, in process_bridges_in_huc
    catchments_df = gpd.read_file(catchments)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 297, in _read_file
    return _read_file_fiona(
  File "/usr/local/lib/python3.10/dist-packages/geopandas/io/file.py", line 338, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
  File "/usr/local/lib/python3.10/dist-packages/fiona/env.py", line 408, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/fiona/__init__.py", line 264, in open
    c = Collection(path, mode, driver=driver, encoding=encoding,
  File "/usr/local/lib/python3.10/dist-packages/fiona/collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 540, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: /fim_temp/fim_4_5_2_5/16040203/branches/8954000027/gw_catchments_reaches_filtered_addedAttributes_crosswalked_8954000027.gpkg: No such file or directory
Command exited with non-zero status 1
```
---------------------

This was detected even before running post processing on that output folder, but running the command line script grep scanning logs for errors.  ie) grep -H -r -i -n "error" ./logs/ > ./all_errors_from_logs.log.  That error file results are in the 4.5.2.5 output folder.

I will now run post-processing to see if other types of errors are discovered.

### LINKED ISSUE #1214: [5pt] Handle system exits with `FIM_exit_codes`
A few scripts in `fim_pipeline.sh` handle abnormal conditions with `sys.exit()`, `sys.exit(0)`, or `sys.exit(1)`. These should be handled with `FIM_exit_codes` in order to prevent hidden downstream pipeline errors caused by missing files, etc. See #1212 for an example.

### LINKED ISSUE #1215: [5pt] src optimization error HydroID for calib not found
This one may not necessary need be a bug, but needs to be evaluated to see if a bigger issue exists. During a full BED run of 4.5.2.5, hundreds, true count unknown, recorded the following errors:

ERROR: HydroID for calb point was not found in the hydrotable (check hydrotable)

ie) 
/outputs/fim_4_5_2_5/logs/src_optimization/log_spatial_src_adjust.log:12633:ERROR: HydroID for calb point was not found in the hydrotable (check hydrotable) for HUC: 04300108  branch id: 2502000002 hydroid: 15190069
/outputs/fim_4_5_2_5/logs/src_optimization/log_spatial_src_adjust.log:12634:ERROR: HydroID for calb point was not found in the hydrotable (check hydrotable) for HUC: 04300108  branch id: 2502000002 hydroid: 15190069
/outputs/fim_4_5_2_5/logs/src_optimization/log_spatial_src_adjust.log:12635:ERROR: HydroID for calb point was not found in the hydrotable (check hydrotable) for HUC: 04300108  branch id: 2502000002 hydroid: 15190070
/ou

I didn't scan that file very much but it was clear there were other hucs such as 01090004.  I can find more applicable hucs and suspect it could be a significant number.  

This was discovered by the new post_processing error scan for all of the log files including all logs being created in post processing. However, this error has not been seen before this build.  There are no other log details available but the code that throughs it can be found at `src_roughness_optimizations.py`

It might be that this needs to be changed to use word warning instead of error, but the fact that it just started suggests a bigger issue.

### PR DESCRIPTION
**Pull request by mluck**
Adds `NO_VALID_CROSSWALKS` to `FIM_exit_codes` which is used when the crosswalk table or output_catchments DataFrame is empty in `add_crosswalk.py` as a result of #1205. Removes branches that fail with `NO_VALID_CROSSWALKS`. Fixes #1212 and fixes #1215 and resolves #1214.

### Changes

- `src/`
    - `add_crosswalk.py`: Added `NO_VALID_CROSSWALKS` as exit status when crosswalk or output_catchments is empty
    - `process_branch.sh`: Removes branches that fail with `NO_VALID_CROSSWALKS`
    - `utils/fim_enums.py`: Added `NO_VALID_CROSSWALKS` to `FIM_exit_codes`

### Testing
Ran `fim_pipeline.sh` on HUC 16040203 (the HUC that errored out in #1212). Branch 8954000027 exited with `Exit status: 64` during `add_crosswalk.py` and did not continue to produce an error in `heal_bridges_osm.py` as in #1212 (the end of the branch log is below).
```
Finalize catchments and model streams 16040203 8954000027
No relevant streams within HUC boundaries.
Command exited with non-zero status 64
	Command being timed: "/foss_fim/src/run_by_branch.sh 16040203 8954000027"
	User time (seconds): 42.92
	System time (seconds): 16.59
	Percent of CPU this job got: 62%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:34.75
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 357548
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 875460
	Voluntary context switches: 17460
	Involuntary context switches: 851098
	Swaps: 0
	File system inputs: 324480
	File system outputs: 400328
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 64
```

### Deployment Plan (For developer use)

_How does the changes affect the product?_
- [x] Code only?
- [ ] Require new or adjusted data inputs? Does it have start, end and duration code (in UTC)?
- [ ] If new or updated data sets, has the FIM code been updated and tested with the new/adjusted data (subset is fine, but must be a subset of the new data)?
- [ ] Require new pre-clip set?
- [ ] Has new or updated python packages?
- [ ] If applicable, has a deployment plan be created with the deployment person/team?

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [ ] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
In looking at the error log files more in depth, I found some lines that are likely related.


/outputs/fim_4_5_2_5/logs/src_optimization/log_usgs_rc_src_adjust.log:53806:ERROR occurred while writing to catchments gpkg for huc: 05120209 & branch id: 0

/outputs/fim_4_5_2_5/logs/src_optimization/log_usgs_rc_src_adjust.log:53807:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_0" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_0" already exists

/outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:7799:ERROR occurred while writing to catchments gpkg for huc: 12030101 & branch id: 1269000016

/outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:7800:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_1269000016" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_1269000016" already exists

/outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8063:ERROR occurred while writing to catchments gpkg for huc: 12030103 & branch id: 9420000024

/outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8064:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000024" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000024" already exists

/outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8107:ERROR occurred while writing to catchments gpkg for huc: 12030103 & branch id: 9420000023

/outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8108:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000023" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000023" already exists

/outputs/fim_4_5_2_5/logs/log_bankfull_indentify.log:80736:ERROR --> 04300108  branch id: 2502000027 failed (details: *** cannot set a frame with no defined index and a scalar  File "/foss_fim/src/identify_src_bankfull.py", line 216, in src_bankfull_lookup

for huc 04300108, he is a mess and threw a ton of the other errors from [1215 ](https://github.com/NOAA-OWP/inundation-mapping/issues/1215),  src optimization error HydroID for calib not found. I think 04300108 had all of its branches fail which is why the errors above for him. The other HUCs for this new related error, I nothing.

**Comment by mluck** [comment]
> In looking at the error log files more in depth, I found some lines that are likely related.
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_usgs_rc_src_adjust.log:53806:ERROR occurred while writing to catchments gpkg for huc: 05120209 & branch id: 0
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_usgs_rc_src_adjust.log:53807:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_0" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_0" already exists
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:7799:ERROR occurred while writing to catchments gpkg for huc: 12030101 & branch id: 1269000016
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:7800:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_1269000016" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_1269000016" already exists
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8063:ERROR occurred while writing to catchments gpkg for huc: 12030103 & branch id: 9420000024
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8064:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000024" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000024" already exists
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8107:ERROR occurred while writing to catchments gpkg for huc: 12030103 & branch id: 9420000023
> 
> /outputs/fim_4_5_2_5/logs/src_optimization/log_ras2fim_rc_src_adjust.log:8108:Error details: Could not add feature to layer at index 0: sqlite3_exec(CREATE TABLE "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000023" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" POLYGON, "HydroID" INTEGER, "S0" REAL, "LengthKm" REAL, "LakeID" REAL, "From_Node" TEXT, "To_Node" TEXT, "NextDownID" TEXT, "areasqkm" REAL, "feature_id" REAL, "distance" REAL, "order_" INTEGER, "src_calibrated" TEXT, "obs_source" TEXT, "calb_coef_final" REAL)) failed: table "gw_catchments_reaches_filtered_addedAttributes_crosswalked_9420000023" already exists
> 
> /outputs/fim_4_5_2_5/logs/log_bankfull_indentify.log:80736:ERROR --> 04300108 branch id: 2502000027 failed (details: *** cannot set a frame with no defined index and a scalar File "/foss_fim/src/identify_src_bankfull.py", line 216, in src_bankfull_lookup
> 
> for huc 04300108, he is a mess and threw a ton of the other errors from [1215 ](https://github.com/NOAA-OWP/inundation-mapping/issues/1215), src optimization error HydroID for calib not found. I think 04300108 had all of its branches fail which is why the errors above for him. The other HUCs for this new related error, I nothing.

I ran `fim_pipeline.dh` on 16040203, 05120209, 12030101, 12030103, and 04300108. After the addition of code to remove branches that fail with the new exit code, this feature branch got rid of all of the post-processing errors noted above with the exception of 04300108, of which there were 181 errors.

**Comment by RobHanna-NOAA** [comment]
Tested against 16040203 and it looks good.

**Review by RobHanna-NOAA — APPROVED** [review]
Looks great.

**Review by RobHanna-NOAA — APPROVED** [review]
Looks good. I ran 1219 first to double check the relationship of the two PRs and it was fine. Then I temporarily merged 1219 into this one 1216 and it was great. I had four branch errors under code 64 as expected

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
