### PR TITLE
[1pt] PR: Snap crosswalk to NWM streams

### LINKED ISSUE #1194: Bad crosswalks along the Brazos River 12070104
Feedback from Katie Laundry that there was some ugly overestimated FIM along the Brazos River near Brazoria, TX (12070104). After a quick review I noted erroneous crosswalks in branch 0. The screenshot below is highlighting numerous hydroids (tan catchments) that are being incorrectly crosswalked to the mainstem Brazos River (red featureid segment) rather than the small tributary that transects these catchments (green featureid segment). 

Image

The blue inundation shown is the 2yr NWM inundation. Note that there are likely additional crosswalking issues in this region.

### PR DESCRIPTION
**Pull request by mluck**
Snaps crosswalk from the midpoint of DEM-derived reaches to the nearest point on NWM streams within a threshold of 100 meters. DEM-derived streams that do not locate any NWM streams within 100 meters of their midpoints are removed from the FIM hydrofabric and their catchments are not inundated. Fixes #1194.

### Changes

- `src/add_crosswalk.py`: Locates nearest NWM stream to midpoint of DEM-derived reaches if within 100 meters. Also fixes a couple of minor bugs. 

### Deployment Plan (For developer use)

_How does the changes affect the product?_
- [x] Code only?
- [ ] Require new or adjusted data inputs? Does it have start, end and duration code (in UTC)?
- [ ] If new or updated data sets, has the FIM code been updated and tested with the new/adjusted data (subset is fine, but must be a subset of the new data)?
- [ ] Require new pre-clip set?
- [ ] Has new or updated python packages?
- [ ] If applicable, has a deployment plan be created with the deployment person/team?

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [ ] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [ ] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by mluck** [comment]
Inundation in 18100201 in the oval area was reported to be false. The current feature branch `dev-extend-fix-snap-crosswalk` corrects the crosswalking error in the DEM-derived reaches (red dashed lines) and removes the inundation.

image

**Comment by mluck** [comment]
The current feature branch `dev-extend-fix-snap-crosswalk` removes the DEM-derived reaches and catchments if no NWM stream is found within 100 meters of the midpoint of the DEM-derived reach. The effect is that there are areas with no catchments in the HUC (left). However, those areas may be inundated by other branches as displayed in the mosaicked image on the right.

image

**Review by ZahraGhahremani — APPROVED** [review]
I tested a few HUCs, and the code is working as expected. It removes DEM-derived reaches if they’re not within 100 meters of NWM streams. Here are examples from HUC 19020602, 21010004, and 1060001. The red lines show the DEM-derived streams, and the green lines are the NWM streams. For HUC 1060001, the catchment was previously inundated by some DEM-derived reaches (fim_4_5_2_0), but they’re not affected in the current feature branch since they don’t have NWM streams within 100 meters of their midpoints. This PR doesn’t have any unintended effects.
FIM
snap

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Comment by mluck** [comment]
Results of the evaluation of the crosswalk using the intersection method (using `tools/evaluate_crosswalk.py`) in the BED HUCs (n=2153):
- The mean evaluation increased from 96.8% to 97.4%
- Evaluation for 1632 HUCs increased, 11 unchanged, and 510 HUCs decreased

**Comment by mluck** [comment]
More detailed overall stats comparing `fim_4_5_2_11 - fim_4_4_15_0`:
```
count    2153
mean        0.006315
std         0.015147
min        -0.078818
25%         0.000048
50%         0.003039
75%         0.007652
max         0.222222
```

I looked at the HUC that decreased the most. The low performance highlights a known limitation in the evaluation test rather than a reduction in the crosswalk accuracy. For example, in the image below, the midpoint of the DEM-derived reach (dashed red line) is correctly crosswalked to the green NWM feature_id via the snapping method, but the evaluation that compares the number of intersections in the DEM-derived reaches and the NWM streams has more intersections with the solid red NWM stream than the green NWM stream.
image

**Comment by CarsonPruitt-NOAA** [comment]
That's great! I'll count this as a pretty big win.

**Pull request merged**
