### PR TITLE
[1pt] PR: Mask levee-protected areas from DEM

### LINKED ISSUE #759: [21pt] Revise levee-protected areas algorithm to avoid "slivers" of inundation at edges of leveed areas
Inundated areas larger than levee-protected areas often leave linear "slivers" of inundation after the levee-protected areas are masked from inundation.

### PR DESCRIPTION
**Pull request by mluck**
Masks levee-protected areas from DEM in branch 0 and two highest stream order branches to prevent slivers of inundation along the perimeter of levee-protected areas. Masking the DEM causes the same levee-protected area to be masked in the REM as well as the pixel catchments of any stream pixels in the leveed area. Closes #759 

## Additions

- `src/gms/`
    - `mask_dem.py`: Masks levee-protected areas from DEM in branch 0 and two highest stream order branches
    - `src/gms/delineate_hydros_and_produce_HAND.sh`: Adds `src/gms/mask_dem.py`

## Testing

1. Ran `src/gms/mask_dem.py` on branch 0 of HUC 12030109 to verify correct masking of DEM.
2. Ran `Inundate_gms` and `Mosaic_inundation` on HUC 12030109 to verify effect of masking DEM on REM and final inundation.

## Screenshots
1. DEM (`dem_meters_0.tif`) with levee-protected areas masked
image

2. Depth raster (`depth_12030109_0.tif`): brown areas are low, positive (correct) depth values that will be inundated; green areas are high (incorrect) depth values that result from erroneous masking (fixed by #767) and will not be inundated after 
image

## Notes

- Depends on #767 for proper results

### CODE REVIEW

**Review by RobHanna-NOAA — DISMISSED** [review]
Ran three hucs with similar scenarios, "12030109 12030105 12030103", then syth and eval on just these three hucs. Compared the outputs to fim_4_0_12_1 adn fim_4_0_13_1.  Slight gains on nws and a slight drop on the ble huc.  Not significant enough to worry about.

Did not compare results from masking at the dem level verses masking against rem raster as per PR [767](https://github.com/NOAA-OWP/inundation-mapping/pull/767).

**Comment by mluck** [comment]
I verified that branches with order less than max(order) - 1 are not being masked. In the example from 12030105 (max(order) = 6), the branch 0 REM (in gray) is masked in levee-protected areas (dotted) while the REM for order 3 branch 1454000008 (in color) is not masked in the leveed areas.
image

**Comment by RobHanna-NOAA** [comment]
Keep the branch open (aka.. don't delete it). more changes and a separate PR are coming later.

**Review by BradfordBates-NOAA — APPROVED** [review]

**Review by RobHanna-NOAA — APPROVED** [review]

**Comment by mluck** [comment]
I computed the proportion of levee-protected area in each of the categories
- `high`: leveed area covered only by top two stream order branches (`order_` >= max(`order_`) - 1)
- `low`: leveed area covered only by the rest of the stream order branches (3 <= `order_` < max(`order_`) - 1)
- `both`: leveed area covered by both low and high stream order branches

The `high` areas are being masked and never inundated, the `low` areas are not masked, and for `both`: the leveed area is covered by both high (masked) and low (unmasked) branches. The `both` allow for situations like inundation by tributaries behind a levee that is protecting an area from inundation on the mainstem. The `low` are the "bad" ones because those levees are most likely protecting against the branch that we're failing to mask. Branch 0 (which would cover a HUC with `high` is not included in this analysis.

The resulting proportions are
- `high`: 0.143
- `low`: 0.103
- `both`: 0.754

```
import os
import numpy as np
import geopandas as gpd
import pygeos as pg

def define_category(row):
    if row['Group_1'] == 'High':
        if row['Group_2'] == 'Low':
            return 'Both'
        else:
            return 'High'
    else:
        return 'Low'

hydrofabric_dir = '/data'
version_name = 'fim_4_0_9_2'

run_dir = os.path.join(hydrofabric_dir, 'outputs', version_name)

levee_protected_areas = gpd.read_file('/data/inputs/nld_vectors/Levee_protected_areas.gpkg')
levee_protected_areas['dissolve'] = 1
levee_protected_areas = levee_protected_areas.dissolve(by='dissolve')
wbd8 = gpd.read_file('/data/inputs/wbd/WBD_National.gpkg', layer='WBDHU8')

# # Intersect leveed areas with wbd to find leveed hucs
leveed_wbd8 = gpd.sjoin(levee_protected_areas, wbd8)
leveed_hucs = leveed_wbd8.HUC8.unique()

area_both = 0.
area_high = 0.
area_low = 0.

for n, huc in enumerate(leveed_hucs):
    print(f'{n+1}/{len(leveed_hucs)}: {huc}')

    wbd_file = os.path.join(run_dir, huc, 'wbd.gpkg')
    branch_polygons = os.path.join(run_dir, huc, 'branch_polygons.gpkg')
    if os.path.exists(branch_polygons) and os.path.exists(wbd_file):
        wbd = gpd.read_file(wbd_file, layer='WBDHU8')
        branch_polygons = gpd.read_file(branch_polygons, layer='branch_polygons')

        leveed = os.path.join(run_dir, huc, 'LeveeProtectedAreas_subset.gpkg')
        if os.path.exists(leveed):
            leveed = gpd.read_file(leveed, layer='LeveeProtectedAreas_subset')
        else:
            leveed = levee_protected_areas

        branch_polygons = gpd.clip(branch_polygons, wbd)
        leveed = gpd.clip(leveed, wbd)
        leveed['all'] = 1
        leveed = leveed.dissolve(by='all')

        max_order = branch_polygons.order_.max()

        branch_polygons.loc[branch_polygons.order_ >= max_order - 1, 'Group'] = 'High'
        branch_polygons.loc[branch_polygons.order_ < max_order - 1, 'Group'] = 'Low'

        branch_polygons = branch_polygons.explode()

        branch_polygons_groups = branch_polygons.dissolve(by='Group', as_index=False)
        if len(branch_polygons_groups.geometry) > 1:
            branch_polygons_union = gpd.overlay(branch_polygons_groups[branch_polygons_groups['Group'] == 'High'], branch_polygons_groups[branch_polygons_groups['Group'] == 'Low'], how='union')

            branch_polygons_union['Category'] = branch_polygons_union.apply(lambda row: define_category(row), axis=1)

        else:
            branch_polygons_union = branch_polygons_groups
            branch_polygons_union['Category'] = branch_polygons_groups['Group']

        round = np.vectorize(lambda geom: pg.apply(geom, lambda g: g.round(3)))
        leveed.geometry = round(leveed.geometry.values.data)
        branch_polygons_union.geometry = round(branch_polygons_union.geometry.values.data)

        levee_categories = gpd.overlay(leveed, branch_polygons_union, how='intersection')
        area_both += levee_categories[levee_categories['Category'] == 'Both'].area.sum()
        area_high += levee_categories[levee_categories['Category'] == 'High'].area.sum()
        area_low += levee_categories[levee_categories['Category'] == 'Low'].area.sum()

total_area = area_both + area_high + area_low

print(area_both/total_area, area_high/total_area, area_low/total_area)
```

**Pull request merged**
