### PR TITLE
[1pt] PR: Fixed datatype issue in coord accuracy list

### PR DESCRIPTION
**Pull request by BradfordBates-NOAA**
At least one site (TRYM7) has not been getting mapped in Stage-Based CatFIM, despite having all of the acceptable accuracy codes. This was caused by a data type issue in the acceptable_coord_acc_code_list in tools_shared_variables.py having 5 as a string instead of an integer.

## Changes

- `/tools/tools_shared_variables.py`: Added an integer `5` to the `acceptable_coord_acc_code_list`

## Testing

1. Ran stage-based catfim for TRYN7 and confirmed that mapping is now occurring.

### CODE REVIEW

**Comment by LauraKeys-NOAA** [comment]
Noted that we might want to restructure the accuracy code checks in the future to cast as strings in case further integer dtype errors pop up

**Comment by BradfordBates-NOAA** [comment]
@LauraKeys-NOAA Did you mean to close this PR?

**Comment by LauraKeys-NOAA** [comment]
yes, didn't know it was still being worked on

**Comment by BradfordBates-NOAA** [comment]
@LauraKeys-NOAA You'll just need to "Approve" when ready, so it can be merged.

**Review by LauraKeys-NOAA — DISMISSED** [review]

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
