### PR TITLE
[1pt] PR: Replace GRASS with Whitebox

### LINKED ISSUE #706: [1pt] Improve efficiency of agreedem.py
`agreedem.py` contains some inefficiencies and outdated code, including loading and closing several of the same raster files multiple times. Also suggest opening rasters using `with`.

See suggested edits in `dev-update-agreedem`

## Current behavior
Multiple files are opened and closed repeatedly but this is unnecessary and inefficient:
- `elev = rasterio.open(dem)` and `elev.close()` are used three times.
- `vectdist = rasterio.open(vectdist_grid)`, `vectallo = rasterio.open(vectallo_grid)`, and `rivers = rasterio.open(rivers_raster)`  and their respective `.close()` are used twice.

### LINKED ISSUE #756: [13pt] Remove Grass from solution
Found in r_grow_distance.py and possibly some other places.

Recommended by Yan to be removed for performance reasons. It created perm issues in Windows and EC2's (but both got around it).

Possible alternatives:  Whitebox (Jim found) or Numpy (Matt might have something on this).

Grass would need to be removed from the Dockerfile and whatever its replacement is will likely be added to the Pipfile. Could be needed in Dockerfile but Pipfile is best if possible)

### PR DESCRIPTION
**Pull request by mluck**
Replaces GRASS with Whitebox. This addresses several issues, including Windows permissions and GRASS projection issues. Whitebox also has a slight performance benefit over GRASS. Closes #702 and closes #706 and closes #756.

## Removals

- `src/r_grow_distance.py`: Deletes file

## Changes

- `Dockerfile`: Removes GRASS
- `Pipfile` and `Pipfile.lock`: Adds Whitebox and removes GRASS
- `src/`
    - `agreedem.py`: Removes `r_grow_distance`; refactor to use `with` context and removes redundant raster reads.
    - `adjust_lateral_thalweg.py` and `agreedem.py`: Refactors to use `with` context and removes redundant raster reads
    - `unique_pixel_and_allocation.py`: Replaces GRASS with Whitebox and remove `r_grow_distance`
    - `gms/`
        - `delineate_hydros_and_produce_HAND.sh` and `run_by_unit.sh`: Removes GRASS parameter
        - `mask_dem.py`: Removes unnecessary line

## Testing

1. A full evaluation run was conducted on this branch. The overall effect was neutral (positive values are where Whitebox improved over GRASS).
image

## Notes
This pull request originated as PR #702; however, I was unable to merge that branch from @JamesColl-NOAA's repository so the files were copied to this branch.

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
I did a quick code glance and it looks good.  This will need to be tested in our new EC2 instances as we have temp directories being created on the fly (which is fine), but we need to make sure there are no permissions in EC2 (and fix them if there is). This needs to be done prior to approval, so we don't get caught off guard when we run it over there.

**Comment by RobHanna-NOAA** [comment]
This PR code was merged with dev, which as fim 4.2.0.0 (fim3 remove). Code files were adjusted as some files were moved, others removed. Changelog.md was updated. The Pipfile and Pipefile lock was rebuilt based on the assumption of pytest (from a pending PR merge for fix_unit_tests), plus the ipython 8.10.0 fix was ensured. A new docker container is being built and tested before new checkin.

**Comment by RobHanna-NOAA** [comment]
Did a new alpha domain run with the latest docker container and code from this branch (which includes 4.2.0.0 / gms/fim 3 cleanup) and the alpha domain test was fine. I think I detected very tiny improvements on CSI for nws and usgs.

**Review by RobHanna-NOAA — DISMISSED** [review]
See conversations. Did a brand new alpha domain run today with all of the code in this branch, including the new docker container, and it is fine.

**Review by mluck — COMMENTED** [review]
I built the new image and ran a test HUC (08020301) to verify the latest changes work on my side and it completed without errors.

**Review by RobHanna-NOAA — DISMISSED** [review]

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
