### PR TITLE
[3pt] PR: Modifying long runtimes for  high stream density HUCs in Alaska

### PR DESCRIPTION
**Pull request by ZahraGhahremani**
This PR focuses on reducing long runtimes for some Alaska HUCs with high stream density. GMS now starts at stream order 6 and above, reducing the number of branches per HUC.

### Changes
- `src/derive_level_paths.py`

### Testing
This has been tested for 5 Alaska HUCs. 
The results need to be tested using `tools/inundate_catchment_boundary.py`

### Deployment Plan (For developer use)

_How does the changes affect the product?_
- [ ] Code only?
- [ ] If applicable, has a deployment plan be created with the deployment person/team?
- [ ] Require new or adjusted data inputs? Does it have start, end and duration code (in UTC)?
- [ ] If new or updated data sets, has the FIM code been updated and tested with the new/adjusted data (subset is fine, but must be a subset of the new data)?
- [ ] Require new pre-clip set?
- [ ] Has new or updated python packages?

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Review by EmilyDeardorff — COMMENTED** [review]
I spent some time comparing the outputs from this branch to a previous output (FIM 4.5.2.5). As expected, the dissolved NWM streamlines geopackage has fewer streams in the output. It visually looks a bit sparse in the new version, but if it seems okay (@CarsonPruitt-NOAA thoughts?) then I'll approve!

19020602 before removing ANY stream orders:
image

19020602 in the old FIM version (4.5.2.5):
image

 19020602 from this branch (`dev-runtime-alaska`):
image

**Comment by CarsonPruitt-NOAA** [comment]
I agree that the `dev-runtime-alaska` does look a little sparse. @ZahraGhahremani can you run Riley's catchment boundary tool from `dev-catchment-boundary-tool` on the outputs from this branch and compare them to outputs from `dev` (or v4.5.2.11 previous fim)?

**Comment by ZahraGhahremani** [comment]
Here is the results for HUC 19020503:

Catchment boundary issue (this branch):
image


Catchment boundary issue (fim_4.5.2.11):
image

Catchment boundary issue (this branch):
image

Catchment boundary issue (fim_4.5.2.11):
image

**Comment by ZahraGhahremani** [comment]
Looking closely at the inundation maps and comparing them with fim_4.5.2.11, there are some inundated areas in fim_4.5.2.11 that do not exist in this feature branch.

HUC 19020402, fim_4.5.2.11 (green lines are streamline):
image

HUC 19020402, this branch:
image

Areas that were inundated in fim_4.5.2.11 but are not in this feature branch:
image

**Comment by CarsonPruitt-NOAA** [comment]
This approach is resulting in too much inundation dropping near the confluences, so we're going to try a different direction.

**Pull request closed without merging**
