### PR TITLE
[13pt] PR: Modifying OSM bridge scripts

### PR DESCRIPTION
**Pull request by ZahraGhahremani**
This PR addresses three issues regarding OSM bridges. It dissolves touching bridge lines so each bridge has a single linestring. It also removes abandoned bridge from the dataset and it adds bridge type field to bridge centroids. As part of this PR, `max_hand_ft` and `max_discharge_cfs` columns are added to `osm_bridge_centroids.gkpg`.
The pre-clip and osm bridges were updated following changes in this PR.

### Changes
- `data/bridges/pull_osm_bridges.py`
- `src/heal_bridges_osm.py`
- `src/bash_variables.env`

### Deployment Plan (For developer use)

_How does the changes affect the product?_
- [ ] Code only?
- [ ] If applicable, has a deployment plan be created with the deployment person/team?
- [ ] Require new or adjusted data inputs? Does it have start, end and duration code (in UTC)?
- [ ] If new or updated data sets, has the FIM code been updated and tested with the new/adjusted data (subset is fine, but must be a subset of the new data)?
- [x] Require new pre-clip set?
- [ ] Has new or updated python packages?

Update: Oct 7th:
- Zahra has already run new pre-clips for CONUS and will run pre-clips for Alaska as part of her testing.
- When she is done, she will tell me (Rob) so I can copy it to the 4 other environments before merging.
    (S3, ESIP, Dev1, UCS2)

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by ZahraGhahremani** [comment]
Using dissolve function to merge touching lines works well for addressing #1147, however, it also combines some bridges that should not be considered as a single bridge based on the current dev version and simplify technique. 

HUC 05030101 (Lat 40.5126 N, long: 80.1354 W):
image

**Comment by ZahraGhahremani** [comment]
Example of abandoned bridges that is dropped in this feature branch:

Churchville, NY in HUC `04130003`:
image

image

**Comment by CarsonPruitt-NOAA** [comment]
Awesome work, Zahra. Can you add to the description that you fixed several HUCs that had no bridges because of the duplicate columns?

**Comment by ZahraGhahremani** [comment]
Thanks, Carson! I also added a line to convert polygon outputs into linestrings to be consistent with the previous version.

**Review by AliForghani-NOAA — APPROVED** [review]

**Comment by RobHanna-NOAA** [comment]
New pre-clips loaded into Dev1, UCS2, FIM S3. I will do ESIP later this week.

**Review by RobHanna-NOAA — APPROVED** [review]

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
