### PR TITLE
[1pt] PR: Extend outlet levelpath(s) outside HUC

### LINKED ISSUE #1280: [8pt] GMS catchment being dropped
Looking at the new HAND v4.5.2.11 in the staging server I've seen a couple of locations where it appears that GMS is not running correctly. The screenshot below is from the Sabin River @ Orange, TX (HUC `12010005`). HAND v 4.4.0.0 is on the left and v4.5.2.11 is on the right.
Image

Upon inspection of the v4.5.2.11 data, branch `1477000010` is missing some catchments. I suspect they are being dropped because of the new crosswalking algorithm that drops catchments if it can't snap to a streamline within 100m.
Image

The places I've seen where this is happening seems to be isolated to areas near the coast and seems to be fairly uncommon.

### LINKED ISSUE #1299: [8pt] Levelpath outlets terminate outside of HUC before reaching WBD buffer
The levelpath of the outlet(s) of a HUC may terminate outside of the HUC before it reaches the edge of the DEM, resulting in reverse-flow and faulty networks during pit-filling. This is a similar issue to #1280.

## Current behavior
The light blue (cyan) levelpath ends just outside of the HUC (black line) and doesn't extend to reach the edge of the WBD-buffered DEM (green line). This causes the DEM-derived reaches (red line) to deviate from the NWM streams, and drops segments (red dashed lines) and catchments (shaded areas) of the DEM-derived reaches where the crosswalk snap distance (100 meters) is exceeded.
image

## Expected behavior
The yellow NWM stream segment should be added to the outlet levelpath.
image

### PR DESCRIPTION
**Pull request by mluck**
Extends outlet levelpath(s) outside HUC.

Previously, levelpaths at the outlet of a HUC may not extend to the buffered WBD that is used to clip the DEM, and during pit-filling this results in reverse flow which can cause DEM-derived reaches to deviate from the channel in the DEM and may result in dropped catchments where the midpoint of the reaches exceeds the snap distance from the NWM stream lines.

This PR extends outlet levelpaths in two ways:
- Segments of levelpaths that terminate in waterbodies are removed from the levelpath (#671). If there is a waterbody downstream of the HUC then the outlet reaches may be trimmed such that the outlet no longer reaches the edge of the DEM, which causes a number of cascading issues originating in the pit-filling such that reverse flow in the DEM-derived reaches can result in erroneous flowlines and inundation. This stops trimming levelpaths outside of the HUC. This was originally a separate PR (#1284) but has been merged into this PR. Fixes #1280 and closes #1284.
- Dissolved outlet levelpaths may terminate downstream outside of the HUC (e.g., at a confluence with a larger river) at a point that is within the buffered WBD. These levelpaths are extended by adding on the downstream segment(s) of the HUC's `nwm_subset_streams` layer. The extended levelpath(s) are saved in a new file that is used to create the boolean raster stream network. Closes #1299

### Changes

- `config/`
    - `deny_unit.lst`, `deny_branch_zero.lst`, and `deny_branches.lst`: Adds new file to deny lists
- `src/`
    - `derive_level_paths.py`:  Adds WBD as an input to `stream_network.trim_branches_in_waterbodies()` and adds new argument for new filename.
    - `run_unit_wb.sh`: Adds new argument for new filename.
    - `stream_branches.py`: Selects only segments intersecting the WBD as candidates for removal if they end in waterbodies and adds downstream segment(s) to outlet levelpath(s).

### Testing
- Tested lake fix on branch 1477000010 of HUC 12010005.
- Tested extending levelpath on branch 2582000038 of HUC 08020302. Tested the recursive function on HUCs 11010007 and 11010011.

### Deployment Plan (For developer use)

_How does the changes affect the product?_
- [x] Code only?
- [ ] If applicable, has a deployment plan be created with the deployment person/team?
- [ ] Require new or adjusted data inputs? Does it have start, end and duration code (in UTC)?
- [ ] If new or updated data sets, has the FIM code been updated and tested with the new/adjusted data (subset is fine, but must be a subset of the new data)?
- [ ] Require new pre-clip set?
- [ ] Has new or updated python packages?

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
I think we had some weirdness on this against the CDN and Mexico border, so we hard cut those borders, didn't we? Not sure. But I wonder how this change might affect those, as we do see quite a few rivers crossing the US / Mexican border. Might be worth double checking. Your call though.

**Comment by mluck** [comment]
A comparison of  the current dev (left) and this feature branch (right). The outlet levelpath in green is now extended to the edge of the DEM (brown area), correcting the flow direction and delineation of DEM-derived reaches. Note the difference between the NWM streamline (green) and the DEM-derived reaches (red dotted line) circled in red as well as the missing DEM-derived reaches circled in gray.
image

**Comment by mluck** [comment]
A comparison of the current dev (left) and this feature branch (right). On the left image, downstream of where the levelpath (black) exits the HUC (green), there is a confluence with a larger river that ends the black levelpath. This occurs in the WBD buffer so the levelpath is terminated before it reaches the WBD buffer which is where the DEM is clipped. Because of this, the DEM-derived reaches (red lines) can deviate from the levelpath or be missing as a result of deviating beyond the crosswalk snap distance. Where the red lines are missing, the catchments (gray shading) are also missing. In the image on the right, the levelpath has been extended by the black line segment which fixes the DEM-derived reaches to align with the levelpath and the catchment coverage is complete.
image

**Comment by mluck** [comment]
The yellow lines indicate levelpath segments that have been added by this PR. The red segments show the end of the outlet levelpath. The green shaded area is the HUC area and the dark green line is the WBD buffered polygon which is used to clip the DEM. The image on the right illustrates both the extending of levelpaths where they were previously terminated at the lake, and also extending multiple levelpath outlets.
image

Ultimately, the difference can be seen in the DEMs. The top row is the current `dev` (v4.5.10.0) and the bottom row is this PR. The images on the left are the DEM after burning the levelpaths and the right images are the DEMs after burning followed by pit filling. When the levelpaths don't reach the edge of the DEM (green line), they can be filled in during pit filling such that essentially undoes the streamline burning process and can result in erroneous reverse direction stream networks.
image

**Comment by mluck** [comment]
I ran `fim_pipeline.sh` and checked HUCs 04100006, 05080003, 07110002, 08020302, 11010007, 11010011, and 12010005. I did run `synthesize_test_cases.py` but only one HUC (07110002) had validation data: MCC and CSI for IFC was identical and ras2fim was only very slightly different.

**Comment by ZahraGhahremani** [comment]
I tested this PR for couple of HUCs and it works as it expected. This is an example of HUC `08020302`, branch `25820000038`.

image

**Review by ZahraGhahremani — DISMISSED** [review]
I tested this PR for couple of HUCs and it works as it expected. This is an example of HUC `08020302`, branch `25820000038`.

image

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Comment by mluck** [comment]
This PR improved CSI for BLE and NWS but decreased for RAS.
image

**Pull request merged**
