### PR TITLE
[1pt] PR: Remove `other` folder from `test_cases`

### LINKED ISSUE #775: [5pt] Remove 'other' folder dependency in run_test_case and update symbology files
Clean up test_cases script `other` directory dependency and update symbology files for QGIS and Esri.

### PR DESCRIPTION
**Pull request by mluck**
Removes dependency on `other` folder from `test_cases`. Also updates ESRI and QGIS symbology. Closes #775.

## Removals

- `tools/`
    - `aggregate_metrics.py` and `cache_metrics.py`: Removes reference to `test_cases/other` folder

## Changes

- `config/symbology/`
    - `esri/agreement_raster.lyr` and `qgis/agreement_raster.qml`: Updates label from `Waterbody mask` to `Masked` since mask also now includes levee-protected areas
- `tools/`
    - `eval_alt_catfim.py` and `run_test_case.py`: Updates waterbody mask to datasets located in `/inputs` folder

## Testing

1. Removed `test_cases/other` and then ran `tools/synthesize_test_cases.py`. Inundation produced correctly masked images.

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
After this gets merged.. the test_cases/other folder can be removed?  (nothing needs to be copied out?)

**Comment by mluck** [comment]
> After this gets merged.. the test_cases/other folder can be removed? (nothing needs to be copied out?)

Yes, `test_cases/other` can be removed without any other related actions necessary. Evaluation will use existing datasets in `/inputs` as masks

**Review by BradfordBates-NOAA — APPROVED** [review]

**Comment by BradfordBates-NOAA** [comment]
Merged. @RobHanna-NOAA please go ahead and remove directories as discussed in comments above.

**Comment by RobHanna-NOAA** [comment]
Yes, thank you. I will leave them there for a while for testing against older versions (and fim3), but put it on my list to remove later.

**Pull request merged**
