### PR TITLE
[1pt] PR: Update benchmark flows in AHPS domain

### LINKED ISSUE #1089: [5pt] There were some "bad" AHPS sites that may work with FIM v4.x
The `BAD_SITES` variable defined in `/tools/tools_shared_variables.py` contains several sites where the mainstems model from FIM v3.x limited the inundation and caused us to not evaluate there. These sites identified by "mainstems does not extend sufficiently upstream" or "no mainstems nearby" should be re-tested with FIM v4.x.

### LINKED ISSUE #1092: [13pt] Update AHPS benchmark flow files to run upstream of 1st gages
This is a follow-up on #1089 to edit the benchmark flow files to include the upstream mainstem feature_ids.

### PR DESCRIPTION
**Pull request by mluck**
Extends flows (i.e., discharge) to stream segments missing from NWS or USGS validation flow files. The levelpath associated with existing flows in the AHPS domain is identified, and any stream segments of the levelpath in the domain missing from the flow file are added to the flow file by assigning the existing flow (this is a constant value regardless of other tributaries including other levelpaths in the domain).

Closes #1089 and closes #1092.

### Additions

- `data/extend_benchmark_flows.py`: Adds missing flows to NWS or USGS benchmark flow files. The original flow file is saved with an appended `.bak`.

### Changes

- `tools/tools_shared_variables.py`: Removed corrected flow files from `BAD_SITES` list.

### Testing

Verified that the new flow files contain the added `feature_id`/`discharge` values from missing stream segments. Also ran `synthesize_test_cases.py` to generate inundation agreement rasters.

##### Flow file (added segments in red)
image

##### Inundation agreement raster (before/after)
image

### Issuer Checklist (For developer use)

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g. `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] `pre-commit` hooks were run locally
- [x] Any _change_ in functionality is tested
- [x] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] [CHANGELOG](/docs/CHANGELOG.md) updated with template version number, e.g. `4.x.x.x`
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)
- [x] Add yourself as an [assignee](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) in the PR  as well as the FIM Technical Lead

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date
- [ ] Update the [Citation.cff](/CITATION.cff) file to reflect the latest version number in the [CHANGELOG](/docs/CHANGELOG.md)
- [ ] If applicable, update [README](/README.md) with major alterations

### CODE REVIEW

**Comment by mluck** [comment]
Since the AHPS benchmark flows seem to be (always?) constant within a flow file and there are other sites that seem to be missing flows in the domain (e.g., chin7), what about applying this to all of the AHPS benchmark flows rather than just the ones in the BAD_SITES list?

**Comment by CarsonPruitt-NOAA** [comment]
That makes sense to me.

**Comment by CarsonPruitt-NOAA** [comment]
@mluck Can you add `cart2` to the BAD_SITES list? @derekgiardino has identified this a site on which we shouldn't be doing evaluations.

**Comment by mluck** [comment]
Updated so that all NWS and USGS benchmark flows are updated (not just those in BAD_SITES).

An input to this is a FIM run (e.g., BED) since it uses the derived levelpaths.

**Comment by RyanSpies-NOAA** [comment]
I have a new error -->
Traceback (most recent call last):
  File "//foss_fim/data/update_benchmark_flows.py", line 134, in <module>
    update_benchmark_flows(**args)
  File "//foss_fim/data/update_benchmark_flows.py", line 81, in update_benchmark_flows
    assert os.path.exists(levelpath_file), f"Levelpath file {levelpath_file} does not exist"
AssertionError: Levelpath file data/previous_fim/fim_4_4_5_0/04300109/nwm_subset_streams_levelPaths.gpkg does not exist

**Comment by mluck** [comment]
Previously, it was checking to make sure the input file existed, and if it didn't then it threw the AssertionError. Now, if an input file doesn't exist for a location, updating the flows are skipped for that location.

I was able to run this PR on the full set of AHPS benchmarks using fim_4_4_0_0.

**Comment by RyanSpies-NOAA** [comment]
Successfully ran the script for FIM 4.4.3.0
image

**Comment by RyanSpies-NOAA** [comment]
Confirmed that CBST2 flow file is unchanged with this feature branch. The flow file currently includes erroneous main stem flow values for the tributary river reaches (order=4). Will likely need a new ticket to address this.
image

**Comment by RyanSpies-NOAA** [comment]
RGDT2 (13090001) shows a slight regression with the new flow file. It appears that the tributary was erroneously added to the flow file --> 
image
image

**Comment by mluck** [comment]
The stream segments are disconnected which is why the flow is being continued up the tributary instead of the mainstem
image

**Comment by mluck** [comment]
Would it make sense to add a feature to remove flows from feature_ids not on the mainstem levelpath (i.e., tributaries) as part of this PR?

**Comment by CarsonPruitt-NOAA** [comment]
Yeah, I think we could include removing the tributaries as part of this PR. It'll be sort of a benchmark flows overhaul.

**Comment by RyanSpies-NOAA** [comment]
Couple more plots to add here for future reference. The aggregate alpha test scores (NWS & USGS sites) show a nice MCC and CSI improvement as expected:
image
image

**Comment by mluck** [comment]
Flows in tributaries (not on the main levelpath) are now removed from the flow file. Example: flows from `cbst2` NWS moderate magnitude (left: original, right: corrected)
image

**Comment by CarsonPruitt-NOAA** [comment]
Wow, that's a pretty major reduction in feature_ids. Did you confirm that these are accurate?

**Comment by RyanSpies-NOAA** [comment]
With Matt's latest change nearly all of the flow files have been modified (as expected): 
image

**Comment by mluck** [comment]
I used stream order to differentiate the tributary levelpath from the mainstem levelpath, but I found at least one case where there were two levelpaths of the same order in the domain. In case this happens, the flow is attributed to the longer levelpath (length in the domain) and not to the shorter levelpath. This agrees with the validation raster (`gett2`, HUC 12070205):
image

**Comment by RobHanna-NOAA** [comment]
I need more information about deployment. I think it needs a full scale run to get new data, although I think Ryan might have this already completed. If that was time, I need time to deploy to all enviros prior to merge.  Do I have it right that we create a new set of benchmark data we need for Alpha testing?  Same.. I will need time to get it deployed. Do you it to be deployed ahead of any particular build? I am worried about too much coming in one build. Can someone clarify deployment for me?

**Comment by mluck** [comment]
This will generate an updated set of AHPS (NWS and USGS) benchmark flow files based on the current benchmark flow files. For testing, the outputs are all saved to a single folder, but on the actual (i.e., post-testing) run, do NOT set the output option `-o` which will force the new benchmark flow files to overwrite the existing benchmark flow files (after a copy of the originals are saved with a `.bak` extension in the same folder).

Then the new benchmark flow files will need replace the old benchmark flow files (and possibly also copy over the original `.bak` backup copies as well) the enviros prior to alpha testing.

**Comment by CarsonPruitt-NOAA** [comment]
Great news! I wasn't expecting to see any increased overprediction as shown in the Action stages. I'm guessing that's coming from the previously-labeled `BAD_SITES` that we added upstream flows to?

**Comment by RyanSpies-NOAA** [comment]
CBST2 (12090301) now shows a much improved agreement raster which can be attributed to the reduction in FP scores for the tributary domain:
image

**Comment by RyanSpies-NOAA** [comment]
Regarding the increased false alarm values (especially for the USGS sites) - it appears there are a couple of factors at play. I think @CarsonPruitt-NOAA is correct that including some of the previous "bad sites" is a key contributor. Here is NMSO1 as an example:
Previous flow file was not providing flow for the reaches within the evaluation domain (purple flow lines show where the flow file has values) which yielded a lot of false negative scores:
image

Modified flow file is now providing flows for the appropriate reaches (green reaches) and there is a sizeable increase in the false positive scores:
image

**Comment by mluck** [comment]
AHPS data for Alaska are also being processed in #1130.

**Review by RyanSpies-NOAA — APPROVED** [review]
Generated new flow files, successfully ran synthesize test case, and produced eval plots using existing 4.4.13.0 FIM outputs.

Locations that need to receive updated benchmark flow files:

- [ ] EFS
- [ ] Dev1
- [ ] ESIP S3
- [ ] ras2fim S3

**Comment by RobHanna-NOAA** [comment]
Copy the `efs..  /usgs_test_cases/validation_data_usgs/` to all enviros, correct?

**Comment by mluck** [comment]
@RobHanna-NOAA This will update both `usgs_test_cases/validation_data_usgs/` and `nws_test_cases/validation_data_nws/`

**Comment by RobHanna-NOAA** [comment]
Forgot to update. The data has been pushed to all enviros including ras2fim and ras2fim-dev

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
