### PR TITLE
PR: [2pt] Fix for when dropping stream orders 1 and 2 resulted in no remaining …

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
During large scale testing of the new feature for [optionally dropping loading of stream orders 1 and 2](https://github.com/NOAA-OWP/inundation-mapping/commit/45c7d6cb3e9fd4c8c88cb828eb34b89b2219739d), it was discovered that some HUCs and branches were left with no remaining stream segments.  See [issue # 579](https://github.com/NOAA-OWP/inundation-mapping/issues/579) for details. (https://github.com/NOAA-OWP/inundation-mapping/issues/579). 

Upon investigation, the bug is due to gms processing and the relationship of how branches are created overlapping catchment and HUC boundaries. 

The failures exposed events that were neither **errors** nor **true successes**. Sometimes a processing of a HUC (gms unit) or a gms branch needs to be aborted. We found that by removing some streams, it created hundreds of events that were initially being recorded as **errors**. With hundreds existing, it took a great deal of time to extract each unit or branch log and review them. 

Logging and classifying them become important as these types of events get lost in 10's of thousands of log records and more critically, the volume meant other true errors were being buried. 

This fix uses a new system, called the  `Fim (custom) system exit code` feature, that recognize that some events are **neither errors or fully successful**. The new system allows for these types of events to be specially tagged with a special exit code and help identify why the processing of that unit or branch was aborted.  At the end of processing of a unit or branch previously resulted in either a 0 (success) or 1 (failure). These types of events now become an exit code of  a 60 or 61 so developers know exactly why the processing of the unit or branch was aborted.  Similar to exceptions, it will be added to the `non-zero-exit-code.log` to help identify what happened.

Previous versions already has a feature was triggered at the end of processing all units or branches called a `non-zero-exit-code` system. That system would scan all logs looking for a text lines saying "exit status <and a code>".  Enhancement are aded here to further help identify non zero exit code events. Two new folders were created in the root folder inside the output folder named `branch_errors` and `unit_errors` to help identify issues. As each unit or branch has completed being processed, it's thread, via `time and tee files`, detect if it finished with a non zero. If a non-zero was discovered, `time and tee` files make a copy of its current output log and puts it into the new `unit_errors` or `branch_errors` folder. This allows for more run time visualization of errors as they occur instead of at the end of processing of all units/branches.  The previous `non-zero-exit code` feature still exists and runs at the end of the full processing cycle but now puts that file inside its related `unit_errors` or `branch_errors` folder. 

Further the `non-zero-exit code` feature was not always reliable and tended to not be executed if errors were not accurately handled during each threaded processing of a unit or branch.  This has also been corrected.

As part of the new `custom system exit code` feature, a new architecture feature was added using python enums. The allow for a text string and an numeric id to be associated with each other to help that correct codes are being issued. While they can appear to be rather excessive, they are a very common tool feature added into most code solutions. A new file called `fim_enums.py` was created which can contain multiple enum class objects eventually. This first enum called `FIM_system_exit_codes` currently has the two new codes mentioned above, but review of other code classes show where this system can be applied to other code files. One example showed a hard coded exception value of 57 which can be changed to use this enum class. Use of this class helps prevent accidental re-use of a code in another context. It is expected that other enum classes may be added to this fim_enum.py file as the code progresses.

An upgrade was also made to `derive_level_paths_unittests.py` and it's .json file, to test scenarios related to dropping stream orders including catching `custom system exit codes`. Some new unit test files were added for other .py files. This includes split_flows_unittests.py and filter_catchments_and_add_attributes_unittests.py.

A new folder in the `outputs` folder was created named `fim_unit_tests_data_do_not_remove` which we will begin the transition process of keeping all unit test data into this folder. Some unit tests currently point to `gms_example_unit_tests` or other folders to find test data and this will be corrected over time.

In addition, a bug in gms was uncovered. When multiple reaches are dissolved into one branch (level path), some key values such as stream order (`order_`) are applied to the new merged branch. However, each of the concatenated reaches may initially have different stream orders. There was no control to figure out what value should be assigned to the new branch for the merged reaches. Now, the highest stream order of all of the concatenated reaches is applied to the new branch. 

One may asks why the offending branches are not discovered and dropped during the gms_run_unit.sh stage instead of the second phase of branch processing.  For a branch error related to filtering to be discovered, quite a bit of processing per branch needs to be completed for the error to occur.

## File Additions

- `src/`
   - `utils/`
      - `fim_enums.py`:
         - A new class called `FIM_system_exit_codes` was added. This allows tracking and blocking of duplicate codes when a custom system code is required. There are a number of other areas within the entire system which could/should take advantage of this new enum class and will be addressed at a later time.
        

## Changes

- `fim_run.sh`: 
    - Added the gms `non-zero-exit-code` system to `fim_run` to help uncover and isolate errors during processing. Errors recorded in log files within in the logs/unit folder are now copied into a new folder called `unit_errors`.  Further, if the `overwrite` flag was included in the command arguments for fim_run.sh, in past versions, all previous logs were left in place. Those are now all deleted before  processing to avoid confusion between previous runs and the current processing run.

- `gms_run_branch.sh` :
    -  Minor adjustments to how the `non-zero-exit code` logs were created. Testing revealed that grep can run into command length issues and resulted in scanning for non-zero-exit codes was not being done. This resulted in hundreds of errors not being noticeable as errors among the over ~55,000 branch logs that could be created.
    - In previous versions, only the `gms_unit.sh` was aware that **stream order filtering** was being done. Now all branch processing is also aware that filtering is in place. This is due to the fact that certain branches were failing related to filtering and were not being handled correctly. See notes above about branch bugs and `custom system exit codes`.   A new command line argument was added to help notify all branch processing that filtering was in place.
    - Small output adjustments were made to help with overall screen and log readability.  

- `gms_run_unit.sh` :
    - Minor adjustments to how the `non-zero-exit-code` logs were created similar to `gms_run_branch.sh.`
    - Small text corrections, formatting and output corrections were added.
    - A feature removing all log files at the start of the process run were added if the `overwrite` command line argument was added.

- `src/`
   - `filter_catchments_and_add_attributes.py`:
      - Some minor formatting and readability adjustments were added.
      - Additions were made to recognize that some events related to **stream order filtering** were created. This was mostly due to missing flowlines now that the branch was further processed. Trapping these events and adding a new custom system exit code helps track and identify these as well as tell `run_by_branch.sh` to stop remaining processing for that branch.
      - A new argument was added so this file was aware that stream order filtering has occurred.

   - `run_by_unit.sh` (supporting fim_run.sh):
         - As a change was made to sub-process call to `filter_catchments_and_add_attributes.py` file, which is shared by gms, related to reach errors.  Note: It is an example of where a new code for `Fim_system_exit_codes` could be used, but it was not added at this time as it would require extensive testing that was out of scope for this set of upgrades.

   - `split_flows.py`:
      - Some minor formatting and readability adjustments were added.
      - Additions were made to recognize the same type of errors as being described in other files related to branch filtering issues. The new `Fim_system_exit_codes` feature was added as well. 
      - A correction was made to be more precise and more explicit when a gms branch error existed. This was done to ensure that we were not letting other exceptions be trapped that were NOT related to stream flow filtering.
      - A new argument was added so this file was aware that stream order filtering has occurred.

   - `time_and_tee_run_by_unit.sh`:
      - The same system of new system exit codes was added. Once again, note that the values of 61 are hardcoded instead of using the python based `Fim_system_exit_code` system. This is related to limited communication between python and bash.

   - `gms/`
      - `derive_level_paths.py` :  
          - Was upgraded to use the new fim_enums.Fim_system_exit_codes system. This occurs when no streams / flows remain after filtering.  Without this upgrade, standard exceptions were being issued with minimal details for the error.
          - Minor adjustments to formatting for readability were made.

      - `generate_branch_list.py` :  
          - Minor adjustments to formatting for readability were made.

      - `run_by_branch.sh`:
         - Some minor formatting and readability adjustments were added.
         - Additions to the subprocess call to `split_flows.py` were added so it was aware that branch filtering was being used. `split_flows.py` was one of the files that was throwing errors related to stream order filtering. A subprocess call to `filter_catchments_and_add_attributes.py` adjustment was also required for the same reason.

      - `run_by_unit.sh`:
         - Some minor formatting and readability adjustments were added.
         - An addition was made to help trap errors that might be triggered by `derive_level_paths.py` for `stream order filtering`.

      - `time_and_tee_run_by_branch.sh`:
         - A system was added recognize if an non successful system exit code was sent back from `run_by_branch`. This includes true errors of code 1 and other new custom system exit codes. Upon detection, this file immediately makes a copy of the related log file and puts it in the new `branch_errors` folder. This allows for a backup system of errors but also run-time viewing of error as they occur instead of waiting 36 hours to 18 days to uncover errors.
         - Note: System exit codes of 60 and 61 were hardcoded instead of using the values from the new  `FIM_system_exit_codes` due to limitation of communication between python and bash.

      - `time_and_tee_run_by_unit.sh`:
         - The same upgrade as described above in `time_and_tee_run_by_branch.sh` was applied here.
         - Minor readability and output formatting changes were made.

      - `todo.md`
         - An entry was removed from this list which talked about errors due to small level paths exactly as was fixed in this pull request set.

- `unit_tests/`
   - `gms/`
      - `derive_level_paths_unittests.py` :  Added a new unit test specifically testing this type of condition with a known HUC that triggered the branch errors previously described.. 
      - `derive_level_paths_params.json`:
           - Added a new node with a HUC number known to fail.
           - Changed pathing for unit test data pathing from `/data/outputs/gms_example_unit_tests` to `/data/outputs/fim_unit_test_data_do_not_remove`. The new folder is intended to be a more permanent folder for unit test data.
           - Some additional tests were added validating the argument for dropping stream orders.

## Unit Test File Additions:

- `unit_tests/`
   - `filter_catchments_and_add_attributes_unittests.py` and `filter_catchments_and_add_attributes_params.json`:

   - `split_flows_unittests.py' and `split_flows_params.json`

## Testing

A very large amount of testing was done including reviewing a number of output files in QGIS and log files. Dozens of testing scenarios were run for normal successful unit test and branch level tests as well as validating that specific type of failures were handled as expected.  There were three places in the code that could trigger errors related to stream filtering and all are explained above. All three code places, which shared the same failure condition, were tested extensively against a number of HUCS. Testing was done with and without stream order filtering. Tests were done within GMS and also with the classic fim_run.sh system.

A couple of multi-day full BED runs were done as well. The first one uncovered the bulk of the changes in this set as many previous errors were being lost in the sheer volume of output logs. The addition of the `FIM_system_exit_codes` and trapping at the `time_and_tee` levels help significantly with this problem.

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
@RobHanna-NOAA Could you please update the Changelog with the target version being 4.0.3.1?

**Comment by RobHanna-NOAA** [comment]
During a BED (CONUS+) test, which includes all current valid HUC8's, it was discovered that a  fix added during a recent commit (within this pull request) was insufficient.  `[https://github.com/NOAA-OWP/inundation-mapping/pull/557/commits/d4b7adc3cf1618272c41fabd70f2cdcad8fb4eaf]` .

Further, a couple more directly related issues were discovered.
1) A new directly related issue was uncovered and was previously being masked in past code releases prior to and including this pull request. The bug existed for a while in filter_catchments_and_add_attributes.py which tested if a filtered catchment file was created without any valid records and raised an exception. That code had a try/except around it. However, the try/except was incorrect and suppressed any errors that existed.  It was not previously uncovered as it only became a valid error during filtering out of stream orders 1 and 2. That try/catch error has now been fixed in the commit dated Apr 1, 2022 [https://github.com/NOAA-OWP/inundation-mapping/pull/557/commits/d1441b7bf9956c227fc5aced5e41856de916f84d] . 

2) During the BED test, another issue with error logs were discovered. Of the 55,000 branches processed during run, 165 branches were in error, more than expected, and were not recorded in the system called non-zero-exit codes. In previous releases, the non-zero-exit code system, was triggered after processing all units or branches. It would scan all log files looking for exit codes from each unit or branch that were not zero. However, non-zero-exit code system failed to scan files correctly.

While debugging, a temporarily command line script was run which uncovered the 165 branch failures within the 55,000 branches logs that were processed. Unfortunately, scanning the 55,000 log files for the 165 error log files not easy (it even takes a long time just to visually load that may files into a windows. 

A change was made in this commit, a new feature was added which detects branches in error as they occur, log the file along with the rest of the log files, but also make a copy of the log for a branch in error and placed into to a new directory in the HUC folder output. This puts all errors in one directory and all log files in that directory are for branches in error. This new feature of copying log files into a separate folder has been applied to the gms for both units and branches. The non-zero-exit codes system was no longer needed and was removed.

A full BED (CONUS+) test will now be run to validate the new error log handling system.

The original fix mentioned above for trapping the original branch errors in this pull request has temporarily been removed in order to validate the new error log feature.

In the next few days, another commit will be added to this pull request to address the very first branch bug that started this pull request and was related to branches who had no remaining upstream flows after filtering.

**Comment by BradfordBates-NOAA** [comment]
@RobHanna-NOAA To confirm, the most recent BED did complete? Also, I'd like to see how the error/warning messages are being written. Let's tag up

**Comment by RobHanna-NOAA** [comment]
@BradfordBates-NOAA . Yes. a full BED run was successful completed. It showed the 14 unit events, with exit code of 60, and recorded the 158 branch events, with code 61, as expected.

**Comment by BradfordBates-NOAA** [comment]
@RobHanna-NOAA Can you please update the Changelog with a list of all files that were changed and a summary of what changed in them? You can refer to previous merges to get a sense for the style

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
