### PR TITLE
[1pt] PR: FIM4 calibration database engine

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
Copy calibration db code from dev-fim3 into the dev (fim4) codebase. Git history not available.

Also updated making it easier to deploy, along with better information for external contributors.

Changed the system so the calibration database name is configurable. This allows test databases to be setup in the same postgres db / server system. You can have more than one calb_db_keys.env running in different computers (or even more than one on one server) pointing to the same actual postgres server and service. ie) multiple dev machines can call a single production server which hosts the database.

## Changes

- `tools`
    - `calibration-db`
        - `docker-compose.yml`: changed to allow for configurable database name. (allows for more then one database in a postgres database system (one for prod, another for test if needed))
        - `README.md`: updated instructions on setup and usage.

- `README.md`: added text talking about the system.

### Additions

- `tools`
    - `calibration-db`
        - `calb_db_keys_template.env`: a new template version of the required config values and added a new config value (db name).

### Removals

- `tools`
    - `calibration-db`
        - `start_db.sh`: Removed as the command should be run on demand and not specifically scripted because of its configurable location of the env file.
        
## Testing

It was setup and configured with a database name of "calibration-test" (for testing purposes), against a different server. An applicable HUC of 12030102 was processed and ensured the database was created/updated correctly.

This should now be easily setup on external contributors environments, assuming they have the correct calibration db inputs as seen in gms_run_branch.sh

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
I ask that Ryan review it for familiarity with the updates and also that Matt try it external. @mluck it should be easy to setup and documented well for you. If you find the documentation needs adjustment, let me know.

Also.. when this is approved and merged, I will go into our servers that are running the fim3 version and replace it with the new fim4 version.

**Comment by RobHanna-NOAA** [comment]
Ok. I moved the calb_db_template.env to the config folder, updated the tools/calibration-db/README.md text, added text to the root README.md and some minor tidbits. Go ahead and review/test it when you are ready (including directions).

**Comment by mluck** [comment]
I was getting a `psycopg2.errors.UndefinedTable: relation "points" does not exist` error that I'm working to find a fix for. Seems to be something in the config files setup.
```
##########################################################################
Performing SRC adjustments using benchmark point database
##########################################################################
This may take a few minutes...
Connecting to the PostgreSQL database...
Host name: ip-172-31-41-156
PostgreSQL database version:
('PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit',)
Connected to database


Finding all fim_output hucs that contain calibration points...
Traceback (most recent call last):
  File "/foss_fim/src/src_adjust_spatial_obs.py", line 421, in <module>
    run_prep(fim_directory, debug_outputs_option, ds_thresh_override, 
  File "/foss_fim/src/src_adjust_spatial_obs.py", line 387, in run_prep
    ingest_points_layer(fim_directory, job_number, debug_outputs_option, log_file)
  File "/foss_fim/src/src_adjust_spatial_obs.py", line 231, in ingest_points_layer
    huc_list_db = find_hucs_with_points(conn, fim_out_huc_list)
  File "/foss_fim/src/src_adjust_spatial_obs.py", line 189, in find_hucs_with_points
    cursor.execute("SELECT DISTINCT H.huc8 FROM points P JOIN hucs H ON ST_Contains(H.geom, P.geom) WHERE H.huc8 = ANY(%s);", (fim_out_huc_list,))
psycopg2.errors.UndefinedTable: relation "points" does not exist
LINE 1: SELECT DISTINCT H.huc8 FROM points P JOIN hucs H ON ST_Conta...
                                    ^
```

**Comment by mluck** [comment]
There seems to be some sort of conflict caused by reading the database credentials in `config/calb_db_keys_template.env` in two different ways. If each of the environment variables in that file are preceded with `export` then initializing the db with docker-compose fails with a message `ERROR: In file /home/matt/git/inundation-mapping/config/calb_db_keys.env: environment variable name 'export CALIBRATION_DB_HOST' may not contain whitespace.` However, if the `export` is removed then the db will start up fine but `src_spatial_adjust_obs.py` fails to connect to the db (copied below). The connection does work if `export` is added back to the parameters.
```
##########################################################################
Performing SRC adjustments using benchmark point database
##########################################################################
This may take a few minutes...
Connecting to the PostgreSQL database...
Waiting for database to come online
Waiting for database to come online
Waiting for database to come online
Waiting for database to come online
Waiting for database to come online
Waiting for database to come online
unable to connect to calibration db
```

**Review by mluck — DISMISSED** [review]
Seems to work fine with the latest changes.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
