### PR TITLE
[1pt] PR: Adding step to trim catchments from levelpath

### PR DESCRIPTION
**Pull request by JamesColl-NOAA**
Addressing #560 , this fix in `run_by_branch` clips catchments which do not intersect the NWM levelpath they were derived for.

# Highlights:
* No modification to I/O data formats
* slight changes to outputs: smaller extent of inundation
* Extra intermediates generated:
  * toy vrt called _$branch/trim_catch_
  * a copy of the catchments prior to trimming called _&branch/gw_catchments_reaches_untrimmed$current_branch_id.gpkg_

# Cleanup:
- [x] Matched code to style of repo
- [x] verified across multiple catchments including NY, HI, and AL
- [ ] determined if results impact FIM performance scores
- [ ] Explore the dropping of very small segments

# Geospatial context:
catch_trim

# Known limitations:
* As outlined above, it is uncertain that this modification improves or degrades FIM performance but should represent an improvement in process.
* Small(er) branches still exercise a fairly large spatial footprint
* Clipping uses st_intersects, which has known issues with geometry precision and subsequently may include catchments at the boarders where a true intersection would not. ex: the extra green catchment in the purple branch on the right side of the watershed.  The alternative (to break this off into a separate process and buffer the linestring geo), is probably a bit excessive.

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
During merge with Dev (which now included the new 'branch 0" system, we had to move the new "trim catchments" code from run_by_branch.sh to delineate_hydros_and_produce_HAND.sh.

**Comment by JamesColl-NOAA** [comment]
After much consternation and iteration, here's that solution.  

# Highlights:
* _trim_catchments.py_ was dropped in favor of modifying _split_flows.py_.
* all processing was relocated to _delineate_hydros_and_produce_HAND.sh_
* No modification to I/O data formats, built off last dev push so you should be able to roll this in without conflict
* Changes to outputs: smaller extent of inundation
* _split_flows.py_ now requires an extra input flag, (-n --nwm-streams-filename) for the _nwm_subset_streams_levelPaths__ geopackage that contaions 'levpa_id' attribute
* Extra intermediates generated: none
* Time added to processing: minimal but untimed, this code is only hit when processing branches higher than 0

# Cleanup:
- [x] Matched code to style of repo
- [x] verified across multiple catchments including NY, HI, and AL, one huc 6 and multiple huc 8's
- [ ] determined if results impact FIM performance scores
- [ ] Explore the dropping of very small segments

# Geospatial context:
Left: DEM streamlines and branch envelopes -- Center: Branch 0 outputs -- Right: Overlaid branch catchments
Trimmed_catchments

# Known limitations:
* As outlined above, it is uncertain if this modification improves or degrades FIM performance but should represent an improvement in process.
* There are several assumptions made in this particular iteration, the most impactful being that:
  * I did it the right way :)
  * The streamlines (both NWM and DEM_derived) are digitized such that the first point is the headwater and the tail is the outlet.  This allows me to assume that, when dissolved by levpa_id the last point in the line is the most downstream point.
  * Along those lines, I have assumed that none of my operations (dissolve, split) alter linestring order.  
  * Python precision issues required me to buffer that point to split.  While the code should handle edge cases, this has not yet been tested at scale.
* Small(er) branches still exercise a fairly large spatial footprint, and seem to be far larger than the FR catchment sizes generated in branch 0.

Let me know if you have any questions.

**Comment by RobHanna-NOAA** [comment]
I (Rob) was bad and renamed a enum class. Was named "FIM_system_exit_codes" and I changed it to FIM_exit_codes.   But this won't be seen until my PR (coming today or tomorrow) for gms_pipeline comes in.  We will need to make 3 minor edits to your split_flows.py but the question will be when. (depends on who gets merged first).  If you get merged first, then I will change it in my PR. If I get merged first, then we need to change yours.

**Comment by RobHanna-NOAA** [comment]
Sorry Jim.  I found a fix that is needed.  Granted it happened when I ran HUC 07080101 with all stream orders (aka.. no filtering), but I feel pretty sure that it would show up in other HUCs even with stream orders 3 and higher.

The error:
	##########################################################################
	Split Derived Reaches 07080101 1480000013
	##########################################################################
	Fri Jul 29 21:33:34 UTC 2022
	Loading data ...
	trimming DEM stream to NWM branch terminus
	Traceback (most recent call last):
	  File "/foss_fim/src/split_flows.py", line 306, in <module>
	    split_flows(max_length, slope_min, lakes_buffer_input, **args)
	  File "/foss_fim/src/utils/shared_functions.py", line 247, in wrapper
	    func(*args, **kwargs)
	  File "/foss_fim/src/split_flows.py", line 112, in split_flows
	    snapped_point['geometry'] = snapped_point.apply(lambda row: target_snapline.interpolate(target_snapline.project( row.geometry)), axis=1)
	  File "/usr/local/lib/python3.8/dist-packages/geopandas/geodataframe.py", line 850, in __setitem__
	    value = _ensure_geometry(value, crs=self.crs)
	  File "/usr/local/lib/python3.8/dist-packages/geopandas/geodataframe.py", line 42, in _ensure_geometry
	    out = from_shapely(data, crs=crs)
	  File "/usr/local/lib/python3.8/dist-packages/geopandas/array.py", line 166, in from_shapely
	    return GeometryArray(vectorized.from_shapely(data), crs=crs)
	  File "/usr/local/lib/python3.8/dist-packages/geopandas/_vectorized.py", line 104, in from_shapely
	    arr[:] = data
	ValueError: could not broadcast input array from shape (0,) into shape (1,)
	Command exited with non-zero status 1
	
------------
the commands I ran:  (both missing the -s switch)
-- gms_run_unit.sh -n rob_jim_4_07080101 -u 07080101 -c /foss_fim/config/params_template.env -j 40 -d /foss_fim/config/deny_gms_unit_default.lst -o
-- gms_run_unit.sh -n rob_jim_4_07080101 -u 07080101 -c /foss_fim/config/params_template.env -j 40 -d /foss_fim/config/deny_gms_unit_default.lst -o

**Comment by RobHanna-NOAA** [comment]
**IMPORTANT: Do not deleted branch** if this gets merged before a different issue is resolved. 
In testing this issue, it exposed another issue with run_test_case.py (as part of alpha testing).  It may be a bit hard to replicate the bug, so lets keep the branch (and this current commit) so the error can be replicated.  The new issue number is [647](https://github.com/NOAA-OWP/inundation-mapping/issues/647).

**Comment by CarsonPruitt-NOAA** [comment]
I also just found this error happen when doing GMS for streams 3+ in HUC `01090004`. It looks like a coastal HUC, so it's a tricky one. I think the right decision is to let this error happen and to define an exit code for this case like we discussed.

We will address this HUC boundary overlap bug at the start of `\gms\run_by_unit.sh` when the NWM streamlines are subset in to the HUC8. That way, there won't be any level path defined for these streams and the HAND catchments will be associated with the proper streams. I opened a new issue #650 that Matt will be addressing.

**Comment by CarsonPruitt-NOAA** [comment]
@JamesColl-NOAA I did find a an error that needs to be addressed. It appears to happen a few times in HUC `11110202` in branches 2, 3, 7, and 8. Please take a look at these and make a determination of what's causing the error. I ran the testing domain and the outputs are here if you want to take a look:
`/data/outputs/_fim4_catch_trim/branches/11110202`

```
##########################################################################
Split Derived Reaches 11110202 7771000002
##########################################################################
Wed Aug  3 19:30:35 UTC 2022
Loading data ...
trimming DEM stream to NWM branch terminus
Traceback (most recent call last):
  File "/foss_fim/src/split_flows.py", line 306, in <module>
    split_flows(max_length, slope_min, lakes_buffer_input, **args)
  File "/foss_fim/src/utils/shared_functions.py", line 247, in wrapper
    func(*args, **kwargs)
  File "/foss_fim/src/split_flows.py", line 112, in split_flows
    snapped_point['geometry'] = snapped_point.apply(lambda row: target_snapline.interpolate(target_snapline.project( row.geometry)), axis=1)
  File "/usr/local/lib/python3.8/dist-packages/geopandas/geodataframe.py", line 850, in __setitem__
    value = _ensure_geometry(value, crs=self.crs)
  File "/usr/local/lib/python3.8/dist-packages/geopandas/geodataframe.py", line 42, in _ensure_geometry
    out = from_shapely(data, crs=crs)
  File "/usr/local/lib/python3.8/dist-packages/geopandas/array.py", line 166, in from_shapely
    return GeometryArray(vectorized.from_shapely(data), crs=crs)
  File "/usr/local/lib/python3.8/dist-packages/geopandas/_vectorized.py", line 104, in from_shapely
    arr[:] = data
ValueError: could not broadcast input array from shape (2,) into shape (1,)
```

**Comment by JamesColl-NOAA** [comment]
After the test domain run and a tag up with @CarsonPruitt-NOAA, it was determined that I continue to overcomplicate this.  GMS allows for out-of-catchment flooding, and prior to splitting at the watershed bounds both the NWM levelpath and DEM derived reach are singular features.  The extra slicing and error checking I was previously performing was unnecessary and has been removed here.  This update should remove all errors with split flows experienced in the test domain, **and masks the errors discovered in #650**.  This was tested by running the split_flows.py modification over all failed branches in the _fim4_catch_trim outputs.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
