### PR TITLE
[1pt] PR: Update FIM3 alpha test to include MS/FR composite analysis

### PR DESCRIPTION
**Pull request by CarsonPruitt-NOAA**
This PR updates `synthesize_test_cases.py` with the ability to create MS, FR, and composite inundation agreement rasters and statistics all in one run. The new composited statistics are output in the same location within each test ID with the `_comp` suffix  replacing `_ms` for each dev or previous_fim run. Addresses #555.
`run_test_case.py` has also been refactored to use a `test_case` python class. This workflow has shown decreased memory usage as compared to the previous version of `run_test_case.py`.

## Changes

- `tools/`
    - `synthesize_test_cases.py`: Merged in `dev` branch (FIM 4) changes and re-factored to run FR, MS, and COMP `run_alpha_test` in that order (with multiprocessing).
    - `run_test_case.py`: Merged in `dev` branch (FIM 4) changes and re-factored to run COMP tests after both FR and MS inundations/test cases are performed.
    - `eval_plots.py`: Ensure that the new `_comp` folder produced in `synthesize_test_cases.py` is included in the plots.
 - `src/`
    - `inundation.py`: Included new data types to prevent memory usage warnings.

## Testing

1. Ran the full set of alpha test HUCs using the command ` python /foss_fim/tools/synthesize_test_cases.py -c PREV -e MS -v fim_3_0_28_1_ms -d fim_3_0_28_1_fr -v -j 8 -m /data/temp/carson/alpha_class_test.csv -o`
2. `python /foss_fim/tools/eval_plots.py -m /data/temp/ryan/alpha_test/fim3_alpha_composite/fim3_alpha_composite.csv -w /data/temp/carson/fim3_alpha_sp -v fim_3_0_28_1_comp -sp`

## Screenshots

New output of `synthesize_test_cases.py` in `/data/test_cases/nws_test_cases/official_versions/02040104_nws/` includes the new `_comp` folder.
image

New output of `eval_plots.py` includes a `comp` folder that contains the plots for composite alpha tests. See next screen for example plot.
image

Alpha test plot showing composite metrics summary (output of `eval_plots.py`).
image

## Notes

-

## Todos

- Update CHANGELOG.md
- Run this branch of the alpha test on the newest release version of FIM that's currently being generated.
- Merge changes to `dev-fim3` into this branch before it gets merged.

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
@CarsonPruitt-NOAA Should this still be draft mode?

**Comment by CarsonPruitt-NOAA** [comment]
@BradfordBates-NOAA Yes, I have a couple more things I want to add before it's ready. It'll be good to go this morning sometime.

**Comment by BradfordBates-NOAA** [comment]
@CarsonPruitt-NOAA it looks like the provided test usage would overwrite the official metrics. You okay with that? An alternative is to copy those outputs to the dev directory and run a dev run.

**Comment by CarsonPruitt-NOAA** [comment]
@BradfordBates-NOAA Either way is fine with me. It might be better to do a `DEV` run to make sure that works okay since I've been using it for `PREV` runs during my testing.

**Review by BradfordBates-NOAA — APPROVED** [review]

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
